- server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/internal/service/JcrModelRepository.java
- server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/internal/service/utils/ModelSearchUtil.java
- server/repo/repo-core/src/test/java/org/eclipse/vorto/repository/service/ModelRepositoryTest.java
- server/repo/repo-ui/src/main/java/org/eclipse/vorto/repository/web/ModelRepositoryController.java
Added functionalities to parse the model search query and choosing the appropriate text search strategy
A search query of the form <i><b>name:ColorLight</b></i> is converted to <i><b>SELECT * FROM SOURCE WHERE name = 'ColorLight'
A search query of the form <i><b>name:ColorLight version:1.0.0</i></b> is converted to <i><b>SELECT * FROM SOURCE WHERE name = 'ColorLight' AND version = '1.0.0'</i></b>
A search query of the form <i><b>name:ColorLight name:Color</b></i>  is converted to <i><b>SELECT * FROM SOURCE WHERE name IN ('ColorLight', 'Color')</i></b>
Signed-off-by: Shiv Kandikuppa <shiv12095@iiitd.ac.in>
> Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=474028

- bundles/org.eclipse.vorto.core/model/Datatype.ecore
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/BooleanPropertyAttribute.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/BooleanPropertyAttributeType.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/DatatypeFactory.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/DatatypePackage.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/EnumLiteralPropertyAttribute.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/EnumLiteralPropertyAttributeType.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/PropertyAttribute.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/impl/BooleanPropertyAttributeImpl.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/impl/DatatypeFactoryImpl.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/impl/DatatypePackageImpl.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/impl/EnumLiteralPropertyAttributeImpl.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/util/DatatypeAdapterFactory.java
- bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/datatype/util/DatatypeSwitch.java
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/Datatype.xtext
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/DatatypeRuntimeModule.java
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/converter/DatatypeValueConverter.java
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/formatting/DatatypeFormatter.xtend
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/formatting/FunctionblockFormatter.xtend
Set measurementUnit to an enumeration literal type so you can do something like this:
```
using com.mycompany.type.Temperature ; 1.0.0
...
mandatory heat as int with { measurementUnit : Temperature.C }
```
Set readable, writable, and eventable to Boolean type.
`mandatory heat as int with { eventable: true, writable : false, readable : false }`
> DSL Improvements for Property

- bundles/org.eclipse.vorto.codegen.ui/src/org/eclipse/vorto/codegen/ui/handler/CodeGeneratorInvocationHandler.java
- bundles/org.eclipse.vorto.codegen.ui/src/org/eclipse/vorto/codegen/ui/handler/ConfigurationElementLookup.java
- bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/model/AbstractModelProject.java
- bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/model/IModelProject.java
- bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/model/MappingResourceFactory.java
Fix for https://github.com/eclipse/vorto/issues/63 - 
Mapping-rules of events are ignored when generating code.
> Fix for https://github.com/eclipse/vorto/issues/63 - Mapping-rules of events ignored

- server/generators/org.eclipse.vorto.codegen.service/src/main/java/org/eclipse/vorto/service/generator/web/utils/ModelZipFileExtractor.java
Errors when infomodel and function block model share similar names. Checking for exact model names instead of partial check. closes #115
> Error during invocation of code generators

- server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/internal/service/JcrModelRepository.java
- server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/model/UploadModelResult.java
Collate all validation errors such that we can show all possible validation errors to the user.
So, if an uploaded model contains both a "model already exist" and "missing model references", both are shown in the UI.
Signed-off-by: erlemantos <erleczar.mantos@bosch-si.com>
> Improve validation error reporting

- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/validation/DatatypeValidator.xtend
There are no requirements for Enums to contain literals. This is so that we don't get an invalid enum when creating a new one.
> Enums are now not required to have literals. Closes #185

- bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/ModelDropListener.java
- bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/ModelDropListenerFactory.java
- bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/ILocalModelWorkspace.java
- bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/ProjectSelectionViewPart.java
Fixes the following:
- #183 With more than one project in the perspective, project selector jumps to first project after Drag & Drop was used
- #184 Expand model element (level:2) after a model was dropped onto it
> Fix for #183 and #184

- bundles/org.eclipse.vorto.perspective/plugin.xml
Closes #270 - Include vorto repository tab in vorto default perspectiveve of eclipse.
> Closes #270 - Include vorto repository tab in vorto default perspective

- server/repo/repository-server/pom.xml
Downgrade the version of the interceptor as there's no higher version in the eclipse repo.
> Downgrade the version of the interceptor

- bundles/org.eclipse.vorto.perspective.vorto/plugin.xml
- bundles/org.eclipse.vorto.perspective.vorto/src/org/eclipse/vorto/perspective/VortoPerspective.java
- bundles/org.eclipse.vorto.perspective.vorto/src/org/eclipse/vorto/perspective/vorto/view/VortoProjectSelectionViewPart.java
Model explorer missing in the Vorto perspective of 0.10.M1 Snapshot version
> Fixes #616 - Model explorer missing in the Vorto perspective

- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/validation/DatatypeSystemMessage.xtend
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/validation/DatatypeValidator.xtend
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/validation/ValidatorUtils.xtend
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/validation/FunctionblockValidator.xtend
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/validation/SystemMessage.xtend
- bundles/org.eclipse.vorto.editor.infomodel/META-INF/MANIFEST.MF
- bundles/org.eclipse.vorto.editor.infomodel/src/org/eclipse/vorto/editor/infomodel/validation/InformationModelValidator.xtend
- bundles/org.eclipse.vorto.editor.infomodel/src/org/eclipse/vorto/editor/infomodel/validation/SystemMessage.xtend
Add validators to check if properties, reference parameters, object return types, and function blocks have an equivalent import statement (using ....)
> Fixes #622

- generators/org.eclipse.vorto.codegen.mqtt.python/src/org/eclipse/vorto/codegen/mqtt/python/PythonDittoSerializerTemplate.xtend
- generators/org.eclipse.vorto.codegen.mqtt.python/src/org/eclipse/vorto/codegen/mqtt/python/PythonSampleTemplate.xtend
- Fixed name of model passed to Serializer
Apologies for the diff, something still seems to be broken on my end, will look into this.
> - Fixed DittoSerializer to be compliant with Ditto format

- generators/org.eclipse.vorto.codegen.kura/src/org/eclipse/vorto/codegen/kura/templates/bluetooth/DeviceBluetoothFinderTemplate.xtend
Don't replace device list if device discovery returns empty, because sometimes, device scan can return 0 devices even if device is present.
> Minor improvement to the generated Kura code. 

- server/devtool/webeditor/src/main/resources/application-local.yml
- server/repo/repository-server/src/main/resources/static/index.html
- server/repo/repository-server/src/main/resources/static/js/directives.js
- server/repo/repository-server/src/main/resources/static/partials/details-template.html
- server/repo/repository-server/src/main/resources/static/partials/search-template.html
Currently the search in the Vorto repository is always resetting after a site change. The idea is to use the location hash to store the state.
Changed:
- search results are now shareable by url (search string, type, pagination and order are stored)
- SearchController will be reloaded after clicking the search tab again
- DetailsController has a link to the previous result if exists
- reload of search result is possible
> Store smart table search state in location hash

- server/repo/repository-server/src/main/resources/static/js/directives.js
- server/repo/repository-server/src/main/resources/static/partials/search-template.html
Using the "hack" from https://github.com/lorenzofox3/Smart-Table/issues/641 the restore of the pagination state is now working.
> Fix pagination start restore from location hash

- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/Functionblock.xtext
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/formatting/FunctionblockFormatter.xtend
- framework/org.eclipse.vorto.core/model/Functionblock.ecore
- website/documentation/appendix/functionblock-dsl-reference.md
Standards like ZigBee allow a device to not implement all commands for a cluster (not 100% sure about OMA LWM2M). Those commands are mandatory or optional. I propose to add a presence parameter to operations in a functionblock. 
```
functionblock MeteringCluster {
...
operations{
optional GetProfileResponse()
optional RequestMirror()
...
}
}
```
> Added presence parameter to operation in functionblock

- framework/org.eclipse.vorto.codegen.ui/src/org/eclipse/vorto/codegen/ui/handler/CodeGeneratorInvocationHandler.java
- framework/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/model/ModelProjectFactory.java
- framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/ModelTreeViewer.java
It would be better to bundle command and current selection. But currently this should solve the issue if someone starts the UI and directly tries to generate some code.
Steps to reproduce the issue:
1. Start eclipse with Vorto Plugin
2. Right click on an information model and select some generator.
3. The error message "Could not retrieve Model Project from selection" appears
Signed-off-by: Simon Pizonka <simon@pizonka.de>
> Workaround for "Could not retrieve Model Project from selection"

- server/repo/repository-web/src/main/resources/static/js/controllers.js
Anytime someone uses the back button on the model details controller all models are reloaded. I try to fix that with this change. I could not find direct side effects. But it mark it as workaround because it looks not that great to have multiple variables to store the same values.
> Save models/filter in root scope to prevent reload on controller change

- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/Datatype.xtext
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/internal/validation/NullableValueValidator.xtend
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/validation/ConstraintValidatorFactory.xtend
- framework/org.eclipse.vorto.core/model/Datatype.ecore
To validate transmitted data it can be helpful to know if it is desired that the value is `null`.
Here is a example where primitive types and also complex types can be marked as nullable:
```
...
status{
mandatory deviceId as int <MIN 1, MAX 54>
mandatory temperature as float <MIN -40, MAX 123.8, NULLABLE true>
mandatory movement as ComplexMovementType <NULLABLE true>
mandatory voltage as float <MIN 0, MAX 3.2, NULLABLE false>
}
...
```
> Allow to mark a property nullable

- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/validation/PropertyConstraintMappingValidation.xtend
Missed this check in my first pull request. Now fixed.
Before:
> Fixed where NULLABLE was highlighted as syntax error

- generators/org.eclipse.vorto.codegen.json/META-INF/MANIFEST.MF
- generators/org.eclipse.vorto.codegen.json/README.md
- generators/org.eclipse.vorto.codegen.json/build.properties
- generators/org.eclipse.vorto.codegen.json/plugin.xml
- generators/org.eclipse.vorto.codegen.json/pom.xml
- generators/org.eclipse.vorto.codegen.json/src/org/eclipse/vorto/codegen/json/JsonGenerator.java
- generators/org.eclipse.vorto.codegen.json/src/org/eclipse/vorto/codegen/json/templates/JsonIMTemplate.java
- generators/pom.xml
This generator outputs the the "EObjects" directly to a json file. This can be useful to read the information model back into another system.
The `pom.xml` maybe looks a bit hack. Had some issues with `maven-bundle-plugin` to include jackson into the package.
> Adding new JSON generator

- server/pom.xml
- server/repo/repository-mapping/pom.xml
- server/repo/repository-web/pom.xml
- server/repo/repository-web/src/main/resources/application-local.yml
The ModelHandle definition is missing in http://vorto.eclipse.org/v2/api-docs. Because of a bug in `springfox-swagger2`(see: https://github.com/springfox/springfox/issues/1282)
Currently the api doc is invalid. Error in Swagger:
> Updated dependencies and added default values to local conf

- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/Functionblock.xtext
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/formatting/FunctionblockFormatter.xtend
- bundles/org.eclipse.vorto.editor.infomodel/src/org/eclipse/vorto/editor/infomodel/InformationModel.xtext
- bundles/org.eclipse.vorto.editor.infomodel/src/org/eclipse/vorto/editor/infomodel/formatting/InformationModelFormatter.xtend
Like in issue #859 discussed category currently does not seems to be used and has more a legacy reason. This pull requests makes category optional.
> Proposal - Make category in IM and FB optional (Fixes #859)

- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/DatatypeRuntimeModule.xtend
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/FunctionblockRuntimeModule.xtend
- bundles/org.eclipse.vorto.editor.infomodel/src/org/eclipse/vorto/editor/infomodel/InformationModelRuntimeModule.xtend
For me the `Source -> Format` in Eclipse had no effect for a functionblock. After some research I have found in the Xtext unit tests (see [Link](https://github.com/TemenosDS/xtext-core/blob/3ba9c9fa57932cb81cac113e0c6a0d4ff9daf553/org.eclipse.xtext.tests/src/org/eclipse/xtext/parsetree/formatter/FormatterTestLanguageRuntimeModule.java)) that `bindIFormatter` needs a return statement.
> Fix source format in eclipse for functionblock, etc.

- .gitignore
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/formatting/DatatypeFormatter.xtend
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/formatting/FunctionblockFormatter.xtend
This removes additional line breaks which are introduced by the braced rule. Adds two line breaks after a description.  
This fixes #857
> Fixes #857 - Removes line wraps before property description

- framework/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/model/AbstractModelElement.java
- framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/labelprovider/DefaultTreeModelLabelProvider.java
If the Ecore model is invalid the filename is used as name.
> Fixes #912 : NullPointerException thrown when the model is invalid

- bundles/org.eclipse.vorto.wizard.vorto/src/org/eclipse/vorto/wizard/datatype/DataTypeFileTemplate.xtend
- bundles/org.eclipse.vorto.wizard.vorto/src/org/eclipse/vorto/wizard/functionblock/FbmodelTemplateFileContent.xtend
- bundles/org.eclipse.vorto.wizard.vorto/src/org/eclipse/vorto/wizard/infomodel/InfomodelTemplateFileContent.xtend
Fixes #909. I also removed the comments from the sections in a functionblock and some spaces. Those are removed anyway during development.
> Fixes #909 - Removed category and comments from templates

- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/Datatype.xtext
I have checked the repository and could not find any model which currently uses "Dictionary" as type.
> Fixes #908 - Using "dictonary" as type name with all lower case letters

- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/Datatype.xtext
- bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/formatting/DatatypeFormatter.xtend
- bundles/org.eclipse.vorto.editor.functionblock.tests/src/org/eclipse/vorto/editor/functionblock/tests/validator/FBExtendsTest.xtend
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/Functionblock.xtext
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/formatting/FunctionblockFormatter.xtend
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/validation/FunctionblockValidator.xtend
- bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/validation/SystemMessage.xtend
- framework/org.eclipse.vorto.core/model/Datatype.ecore
- framework/org.eclipse.vorto.core/model/Functionblock.ecore
I have implemented that if a value is overwritten not all property attributes and constraints have to be written again. They are inherited from the parent FB. I am not sure if this would create more confusion and complications about the behaviour. The editor shows an error message if this rule is violated. Unit test currently not complete.
I am open for a discussion. How do you feel about this @aedelmann? Yes/No would be fine. The other option would be to require all attributes and constraints to be written again. I am a bit undecided here.
**Here some examples:**
```
mandatory xValue as float with { readable: true} 
```
Can be overwritten with:
```
mandatory xValue as float <MAX 100>
```
Evaluated as:
```
mandatory xValue as float with { readable: true} <MAX 100>
```
**Second example:** …
> Added validation for FB extends

- toolset/eclipse/bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/validation/FunctionblockValidator.xtend
Adds to the validation that underscores are also allowed in FBs. If the domain contains a hyphen a underscore should be used just like in Java.
> Allow underscore in namespace

- toolset/eclipse/bundles/org.eclipse.vorto.editor.datatype.ide/META-INF/MANIFEST.MF
- toolset/eclipse/bundles/org.eclipse.vorto.editor.datatype.ide/src/org/eclipse/vorto/editor/datatype/ide/syntaxcoloring/PropertyNameSemanticHighlightingCalculator.xtend
- toolset/eclipse/bundles/org.eclipse.vorto.editor.datatype.ui/src/org/eclipse/vorto/editor/datatype/ui/DatatypeUiModule.xtend
- toolset/eclipse/bundles/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/Datatype.xtext
- toolset/eclipse/bundles/org.eclipse.vorto.editor.functionblock.ui/META-INF/MANIFEST.MF
- toolset/eclipse/bundles/org.eclipse.vorto.editor.functionblock.ui/src/org/eclipse/vorto/editor/functionblock/ui/FunctionblockUiModule.xtend
Now `status`, `events`, `operations`, `configuration` and `fault` are allowed as property name. 
Lets discuss which other keywords make sense to add in a new issue. If I have time I like to create a list of all available keywords.
> Fixes #956 - Allow FB section names as property name

- repository/repository-server/src/main/java/org/eclipse/vorto/repository/core/IModelRepository.java
- repository/repository-server/src/main/java/org/eclipse/vorto/repository/core/impl/JcrModelRepository.java
- repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/AbstractModelImporter.java
- repository/repository-server/src/test/java/org/eclipse/vorto/repository/importer/ModelImporterTest.java
This refactoring was due to the fact that the output of doImport of AbstractModelImporter doesn't actually set the imported flag to true even if in the database, it already is. This fixes it.
> Minor refactoring and add checking of imported flag on unit test.

- core-bundles/language/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/Functionblock.xtext
Use the ValidId ParseRule (ID + keywords) for operation parameters (primitive, dict and ref).
> Fixes #1038 - Use ValidId for operation parameters

- pom.xml
Sonatype is needed for some eclipse plugins.
> Add Sonatype to repositories

- repository/repository-core/pom.xml
- repository/repository-core/src/main/java/org/eclipse/vorto/repository/actuator/GeneratorsHealthCheck.java
- repository/repository-core/src/test/java/org/eclipse/vorto/repository/actuator/GeneratorsHealthCheckTest.java
By default the Error Handler for the Spring Rest-Template throws an
exception when the status code in a response is not 2xx.
Hence the check whether a Generator is available is changed from
checking the status code to handling the exception thrown by the
Rest-Templates error handler.
Signed-off-by: Schmidt-Dumont Georg (BCI/ESW24) <georg.schmidt-dumont@de.bosch.com>
> [1250] Fix error handling in Generators Health check

- pom.xml
MaxPermSize was removed in Java8 so no reason for keeping it.
> Remove MaxPermSize from jvm options

- repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/it/AbstractIntegrationTest.java
Had the problem that the `testSearchModel` test in `RepositoryJavaClientTest` collided with my local database.
> Use H2 database config for integration test

- docs/tutorials/create_webapp_dashboard.md
- docs/tutorials/mqtt-python.md
> **Note** Only merge once vorto-dashboard has been released on NPM
- Adjusts instructions of the dashboard to conform to the npm install workflow
- Adds bridge connection problem fix as a side note if no data is coming in
---
> Add what to do to Tutorials / Update Vorto Dasboard Tutorial with new instructions

- repository/repository-core/src/main/java/org/eclipse/vorto/repository/workflow/impl/SimpleWorkflowModel.java
- repository/repository-core/src/main/java/org/eclipse/vorto/repository/workflow/impl/conditions/HasRoleCondition.java
- repository/repository-core/src/main/java/org/eclipse/vorto/repository/workflow/impl/functions/GrantModelOwnerPolicy.java
- repository/repository-core/src/test/java/org/eclipse/vorto/repository/AbstractIntegrationTest.java
- repository/repository-core/src/test/java/org/eclipse/vorto/repository/workflow/WorkflowTest.java
> Fixes #1575 - Model Promoter is not able to deprecate models in tenant.

- repository/repository-core/src/main/java/org/eclipse/vorto/repository/account/impl/DefaultUserAccountService.java
- repository/repository-core/src/main/java/org/eclipse/vorto/repository/init/RepositoryInitializer.java
- repository/repository-server/src/main/resources/application.yml
This fixes #1591 - Setting multiple admins causes AWS problems
> Revert back the usage of semicolon.

- mapping-engine/docs/mapping_syntax.md
Starting a new documentation file that should give more clearance about the syntax of the mapping specifications.
> The content right is based on the Mapping Engine blog post
> Add mapping syntax basics

- repository/repository-web/dist/css/style.css
- repository/repository-web/dist/partials/details-template.html
> Avoid image distortion

- docker/Readme.md
- docker/vorto-variables.env
- docs/gettingstarted.md
To make the life of a new operator of a vorto repository easier there now
is a section on configuration of 3rd party generators via the PLUGINS
variable.
There is also a link to one of the profile config files containing an
example array of plugins hosted on AWS, so the operator may gain some
insight on how this could look like.
Add reference to docker docs to getting started
The getting started guide should also feature a guide for operators
containing a link to the README of the docker deployment.
Fixes #1991 
Signed-off-by: Alexander Wellbrock <a.wellbrock@mailbox.org>
> Fixes #1991 Add docs and example var for plugin registration

- docker/Readme.md
- docker/vorto-variables.env
- docs/gettingstarted.md
Comment http proxy settings from docker env
It is a more sane value to not set these variables per default with
dummy values. Instead these should be commented out but present for
reference.
Update readme md formatting with linter defaults
Remove plugin apiv1 variables from example
The variables VORTO_URL and SERVICE_URL are not needed anymore in vorto
0.11 and newer, since plugins are now registered via the PLUGINS env
variable.
Fixes #1989
> Fixes #1989 Update the docker docs and variables

- Readme.md
- docs/gettingstarted.md
- docs/tutorials/connect_esp8266.md
- docs/tutorials/connect_javadevice.md
- docs/tutorials/create_mapping_pipeline.md
- docs/tutorials/create_openapi.md
- docs/tutorials/create_thing.md
- docs/tutorials/create_webapp_dashboard.md
- docs/tutorials/describe_device-in-5min.md
- docs/tutorials/describe_device_with_eclipse_ide.md
- docs/tutorials/describe_tisensor.md
- docs/tutorials/extend_mapping_pipeline_with_digital_twin.md
- docs/tutorials/managing_collaborators.md
- docs/tutorials/managing_namespaces.md
- docs/tutorials/mqtt-python.md
- docs/tutorials/publishing_models.md
add "eclipse-vorto" tag parametrization to all "ask a question" links in .md documentation
Edge case:
the "eclipse-vorto" tag has already been created in Stack Overflow. In the _unlikely_ case that it was deleted, the links would still lead to a form containing the tag, but users with less than 1500+ reputation would not be able to post the form unless they remove the tag.
> Add "eclipse-vorto" tag parametrization to all "ask a question" links in .md documentation

- repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/account/SessionTimeoutController.java
- repository/repository-web/dist/css/style.css
- repository/repository-web/dist/js/controllers/detailsController.js
- repository/repository-web/dist/js/controllers/mapping/mappingbuilder-controller.js
- repository/repository-web/dist/js/init/appServiceLoader.js
- repository/repository-web/dist/js/service/sessionTimeoutService.js
- repository/repository-web/dist/partials/details-template.html
- repository/repository-web/dist/partials/mapping/mappingcreator.html
- repository/repository-web/dist/partials/templates/session-timeout-warning.html
To introduce the session timeout warning, I have created a new REST endpoint on the backend that simply returns the HTTP session timeout. 
In the frontend, I have created a new AngularJS service (SessionTimeoutService) that retrieves the configured timeout from the backend and sets a timeout until the warning will be displayed. 
The HTML for the warning is in a separate file that can be included wherever needed. For now it's included in the details and mapping pages. The new CSS class .alert-danger-stick-top sticks the warning to the top of the viewport, so it will always be displayed, no matter where the user scrolled. 
5 minutes before the session expires, the warning will be displayed with a countdown and a button to extend the session. When the session is expired, a message will be …
> Add session timeout warning. Fixes #1735

- docs/tutorials/create_mapping_pipeline.md
Added Device Registration and Device Credentials hints to make it easier for the user to follow the tutorial and prevent getting lost between choosing the device registation and device credentials api.
Signed-off-by: Patrick Sernetz <patrick@sernetz.com>
> Links to device registration and credentials api

- repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java
Removed conditional check that would only validate attachments if not tagged as "IMPORTED"
> bug/2114 Enable Validation for all Attachments

- generators/generator-lambda/generator-lambda-executor/src/main/java/org/eclipse/vorto/plugins/generator/lambda/executor/GeneratorExecutionHandler.java
@aedelmann I have removed the quotation marks from the header (see explanation in my comment in #2168). Or do you see any reason, why this should not be done?
> Remove quotation marks from Content-Disposition header. Fixes #2168

- Jenkinsfile
Signed-off-by: Tobias Gauss <tobias.gauss@bosch-si.com>
> added config option to disable concurrent builds. Fixes #2217

- repository/repository-elasticsearch/src/test/java/org/eclipse/vorto/repository/search/SearchTestInfrastructure.java
Fixed SearchTestInfrastructure with following:
* format string for random installation directory now child of target directory (was child of module root previously)
* amended randomizer utility javadoc with latest functionality
> bug/2229 does not place the ES installation directory for tests under the target directory

- repository/repository-elasticsearch/src/test/java/org/eclipse/vorto/repository/search/SearchTestInfrastructure.java
* set timeout to 1 minute (default was 15 seconds)
> bug/2242 Set a longer timeout for ES integration tests using allegro

- mapping-engine-nodejs/README.md
FotonXPath would also be a cool name, but the project is called fontoxpath.
Thanks for finding and using FontoXPath though!
> Fix typo in references to FontoXPath

- repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/NamespaceController.java
* fixed namespace/tenant equality comparison being too strict wrt to subdomains when checking for user access
> bug/2349 Non-Systemadmin users can't save models

- repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderV2.java
- repository/repository-oauth-boschid/src/test/java/org/eclipse/vorto/repository/oauth/HydraTokenVerifierTest.java
- repository/repository-oauth-boschid/src/test/java/org/eclipse/vorto/repository/oauth/LegacyTokenVerificationTest.java
- repository/repository-server/src/main/resources/application.yml
There was a check in the OAuth handler, that checked whether the OAuth client was a technical user in the namespace of the requested model. IMO this is not necessary as the regular access control applies. 
@mena-bosch maybe have a quick look, to see if you see a reason, why this maybe shouldn't be removed.
> 2380 suite auth access to public models

- repository/pom.xml
* Reverting to jQuery 3.4.1 as I just found an approved CQ that did not pop up in my previous search, and I definitely don't want to open a new CQ unless strictly necessary
> 2426/Upgrade AngularJS to latest stable

- docs/specs/vorto_repository-1.0.yml
Added documentation of the new HTTP endpoint about retrieving links that have been attached to a model to the Swagger documentation.
Signed-off-by: Aadarsh Baid <baidaadarsh@gmail.com>
> Fixes #2651

- repository/repository-web/dist/partials/privacypolicy-dialog.html
- repository/repository-web/dist/partials/privacypolicy-template.html
- Changed "Bosch" to "Bosch.IO" when referred to as a company
- Mentioned Suite Auth as alternate identifier
- Added considerations about e-mail address data processing
- Changed support e-mail to non-Bosch vorto-dev
- Added section detailing user data visibility
- Added reference to existing pre-requisite to terminate Vorto account
> privacy_policy_update
