repo/remoterepository/src/main/webapp/index.html
Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=473372
=> Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=473372

bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/repository/IModelContent.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/repository/IModelQuery.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/repository/IModelRepository.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/repository/IModelResource.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/repository/ModelAlreadyExistException.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/repository/ModelRepositoryFactory.java
This pull request is for Bug 473638 [https://bugs.eclipse.org/bugs/show_bug.cgi?id=473638]
- Added API
- Added javadocs
=> For Bug 473638 - Define API for Repository Access.

bundles/org.eclipse.vorto.perspective/plugin.xml
=> Add Model repository to perspective.

features/org.eclipse.vorto.feature.codegen.examples/feature.xml
Signed-off-by: Alexander Edelmann <alexander.edelmann@bosch-si.com>
=> Added jsonschema and coap generator to generator feature

bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/ModelDropListenerFactory.java, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/dropvalidator/DatatypeValidator.java
=> Don't allow entities to be dropped to enums. Closes #92

bundles/org.eclipse.vorto.core/model/Functionblock.ecore, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/FunctionblockPackage.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/Param.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/EventImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/FunctionblockFactoryImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/FunctionblockModelImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/FunctionblockPackageImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/OperationImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/ParamImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/PrimitiveParamImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/ReturnPrimitiveTypeImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/ReturnTypeImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/util/FunctionblockSwitch.java, bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/Functionblock.xtext, bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/formatting/FunctionblockFormatter.xtend
- Allow users to add descriptions to parameters in the operation.
- Modified formatter to add a linewrap to multiple parameters in the operation, to make it readable.
Closes #119.
=> Allow users to add description to parameters

server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/internal/service/generation/GenerationDelegateProxyService.java, server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/model/GeneratorServiceInfo.java, server/scripts/urls.lst, server/scripts/webmonitor.sh
Vorto Repository and generators monitoring scripts. Closes #130 
Co-Author : Erle Czar Mantos ErleCzarS.Mantos@bosch-si.com
=> Vorto Repository and generators monitoring scripts. Closes #130

server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/internal/service/JcrModelRepository.java, server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/internal/service/validation/ModelReferencesValidation.java, server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/internal/service/validation/exception/CouldNotResolveReferenceException.java, server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/model/UploadModelResult.java
Fixes - #135 Error messages on the share dialog are not reflected in the table. Closes #135
=> Fixed #135 - Error messages on the share dialog are not reflected

bundles/org.eclipse.vorto.perspective/META-INF/MANIFEST.MF, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/util/ViewPartUtil.java, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/ModelRepositoryViewPart.java
Open a shared model in the editor when it is clicked from the model repository browser. Closes #91
=> Open shared model in editor when clicked in repo browser

bundles/org.eclipse.vorto.codegen.ui/src/org/eclipse/vorto/codegen/ui/handler/CodeGeneratorInvocationHandler.java, bundles/org.eclipse.vorto.codegen.ui/src/org/eclipse/vorto/codegen/ui/handler/ConfigurationElementLookup.java
Signed-off-by: erlemantos <erleczar.mantos@bosch-si.com>
=> Use getServiceKey() to match generator and mapping.

server/repo/repo-ui/src/main/resources/application.properties
=> Fix database connection timeout issue; Closes #129

docs/_includes/header.html, docs/_includes/homepageheader.html, docs/css/vorto.css
=> website_homeindex closes #154.

docs/_data/doclinks.yml, docs/documentation/tutorial/mqttwithwebapp.md
=> Improvements to the tutorial.#71

docs/blog/2016-03-11-blogpost.md, docs/blog/2016-05-06-interoperability.md
=> Included a new blog post

targetplatform/vorto.setup
=> Remove redundant project build in oomph setup file, close #173;

server/docker-compose-build.yml
=> Remove redundancy in docker-compose-build.yml file, close #174;

bundles/org.eclipse.vorto.codegen.ui/src/org/eclipse/vorto/codegen/ui/handler/ModelGenerationTask.java, bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/model/InformationModelProject.java, bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/model/nature/VortoProjectNature.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/AbstractModelWizardPage.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/ModelBaseWizardPage.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/VortoProjectCreationTask.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/WizardCreateProjectHandler.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/datatype/AbstractDatatypeWizard.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/functionblock/FunctionBlockWizard.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/infomodel/InfomodelWizard.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/mapping/MappingModelWizard.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/mapping/MappingModellWizardPage.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/vorto/NewVortoProjectHandler.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/vorto/VortoProjectWizard.java, bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/vorto/VortoProjectWizardPage.java
Combining multiple model wizards to single project wizard. Closes #65
=> Combining multiple model wizards to single project wizard

docs/overview/vorto_overview.md
=> Included links for vorto profiles for respective usecases

bundles/org.eclipse.vorto.codegen.ui/plugin.xml, bundles/org.eclipse.vorto.wizard/plugin.xml
Remove individual model wizards for Vorto model project wizards. Closes #190
=> Remove individual model wizards for Vorto model project wizards. Closes #190

docs/_includes/homepagebottom.html
=> Modifed image style to make the company log responsive. Closes #139

bundles/org.eclipse.vorto.core/META-INF/MANIFEST.MF, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/model/ModelId.java
Change the filename references to include version number. Closes #194
=> Change the filename references to include version number. Closes #194

bundles/org.eclipse.vorto.repository/src/org/eclipse/vorto/repository/function/StringToUploadResult.java
Fix for sharing models for older version of Repository. 
Closes #207
=> Fix for sharing models for older version. Closes #207

examples/for-platform-vendor/org.eclipse.vorto.example.cgenerator/.classpath, examples/for-platform-vendor/org.eclipse.vorto.example.cgenerator/src/org/eclipse/vorto/example/CGenerator.java, examples/for-platform-vendor/org.eclipse.vorto.example.cgenerator/src/org/eclipse/vorto/example/template/CHeaderTemplate.xtend
=> Adapting c generator for new mapping api changes

bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/command/DeleteModelAction.java
=> Closes #214 - Removing model reference does not unlink model in perspective

bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/model/AbstractModelElement.java, bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/model/DatatypeModelElement.java, bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/model/FunctionblockModelElement.java, bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/model/InformationModelElement.java, bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/model/MappingModelElement.java, bundles/org.eclipse.vorto.core/model/Functionblock.ecore, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/FunctionblockModel.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/FunctionblockPackage.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/FunctionblockModelImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/FunctionblockPackageImpl.java, bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/Functionblock.xtext, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/listener/ErrorDiagnosticListener.java, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/ProjectSelectionViewPart.java
=> Closes #215 - Allow Functional blocks to extend other Functional blocks

bundles/org.eclipse.vorto.editor.infomodel/3_Generate_Infomodel.launch, bundles/org.eclipse.vorto.editor.mapping/4_Generate_Mapping.launch, targetplatform/vorto.setup
1. Update xtext version to 2.9.2;
2. Add back 2 launch files;
=> Update oomph profile and add back launch files; 

bundles/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/mapping/MappingModellWizardPage.java
Quick fix for 223 but the entire wizard codebase really needs an overhaul.
=> Fix for 223 - Creation of Mapping Models not possible anymore

targetplatform/vorto.setup
=> Remove version check for xtext, and include antlr bundle explicitly; close #259

example-generators/org.eclipse.vorto.codegen.examples.lwm2m/src/org/eclipse/vorto/codegen/examples/lwm2m/templates/FunctionBlockXmlTemplate.java
Adapting Lwm2m template to new dsl changes. Fixing hudson build failures.
=> Adapting Lwm2m template to new dsl changes.

bundles/org.eclipse.vorto.repository/src/org/eclipse/vorto/repository/RestClient.java
=> Closes #282 - Vorto toolset doesn't set the proxy username/password

server/docker-compose.yml, server/generators/org.eclipse.vorto.codegen.service.leshan/Dockerfile, server/generators/org.eclipse.vorto.codegen.service.leshan/pom.xml, server/generators/org.eclipse.vorto.codegen.service.leshan/src/main/java/org/eclipse/vorto/codegen/service/leshan/LeshanGeneratorMicroService.java, server/generators/org.eclipse.vorto.codegen.service.leshan/src/main/resources/.gitignore, server/generators/org.eclipse.vorto.codegen.service.leshan/src/main/resources/application-docker.properties, server/generators/org.eclipse.vorto.codegen.service.leshan/src/main/resources/application-eclipse.properties, server/generators/org.eclipse.vorto.codegen.service.leshan/src/main/resources/application.properties, server/generators/pom.xml
=> add micro-service wrapper for leshan code generator; close 286; 

server/docker-compose-build.yml
=> Remove redundant code in docker-compose-build file; close #288

targetplatform/VortoIDEForPlatformVendor.setup, targetplatform/VortoIdeForDeviceManufacturer.setup, targetplatform/VortoIdeForSolutionDeveloper.setup
=> modify oomph profile to point to nightly snapshot;

targetplatform/VortoIDEForPlatformVendor.setup, targetplatform/VortoIdeForDeviceManufacturer.setup, targetplatform/VortoIdeForSolutionDeveloper.setup
=> update oomph setup files for milestone build and master branch; close #304; 

server/repo/repo-ui/src/main/java/org/eclipse/vorto/repository/web/ModelGenerationController.java, server/repo/repo-ui/src/main/java/org/eclipse/vorto/repository/web/ModelRepositoryController.java, server/repo/repo-ui/src/main/java/org/eclipse/vorto/repository/web/ShareModelController.java
=> improve swagger document; close #210; 

bundles/org.eclipse.vorto.core/model/Functionblock.ecore, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/FunctionblockPackage.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/Operation.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/FunctionblockPackageImpl.java, bundles/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/functionblock/impl/OperationImpl.java, bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/Functionblock.xtext, bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/formatting/FunctionblockFormatter.xtend
=> add breakable keyword

example-generators/org.eclipse.vorto.codegen.examples.lwm2m/src/org/eclipse/vorto/codegen/examples/lwm2m/templates/FunctionBlockXmlTemplate.java
=> fix bug #325 - generate empty operations in lwm2m code generator;

example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/EventValidationTask.java, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/OperationParametersValidationTask.java, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/OperationReturnTypeValidationTask.java, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/template/ConstraintTemplate.xtend, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/template/EntityValidationTemplate.xtend, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/template/OperationParametersValidationTemplate.xtend, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/template/OperationReturnTypeValidationTemplate.xtend, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/template/OperationSingleParameterValidationTemplate.xtend
Enhancments to json schema generator to add DSL constraints for the operations.
=> Enhancments to json schema generator. 

bundles/org.eclipse.vorto.codegen.ui/src/org/eclipse/vorto/codegen/ui/handler/CodeGeneratorTaskExecutor.java, bundles/org.eclipse.vorto.codegen/src/org/eclipse/vorto/codegen/api/IVortoCodeGenerator.java, server/generators/org.eclipse.vorto.codegen.service/src/main/java/org/eclipse/vorto/service/generator/web/CodeGenerationController.java
=> Return error log when code generation fails; fixes #331;

cli/.gitignore, cli/command/download.go, cli/config/client.go
Illegal filenames created on OSX while download on CLI tool. Fixes #50
=> Illegal filenames created on OSX while download. Fixes #50

website/_data/doclinks.yml, website/documentation/code-generators/codegenerators.md, website/documentation/code-generators/m2m-codegenerator.md, website/documentation/code-generators/webdevice-codegenerator.md, website/documentation/installation/installation.md
Signed-off-by: Guenther Michael (INST/BSV2-TD) <Michael.Guenther@bosch-si.com>
=> Example Code Generators. Fixes #251

website/Avorto.md
=> 134_vortoVideo. Fixes #134

server/repo/repo-ui/Readme.md, server/repo/repo-ui/src/main/resources/application-mysql.yml
Mysql Configuration and documentation. Fixes #353
=> Mysql Configuration and documentation. Fixes #353

bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/ModelDropListener.java, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/ModelDropListenerFactory.java, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/DatatypeTreeViewer.java, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/FunctionblockTreeViewer.java, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/InfomodelTreeViewer.java
=> Fixes #339 - Adding Modeldependency empties model.

bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/ModelDropListener.java
=> Fixes #369 - Bug in Drag/Drop from Model Repository Browser

cli/Readme.md
Vorto CLI tool developer Setup Documentation.
=> Vorto CLI tool developer Setup. Fixes #355

website/UpdatesOnTheDSL.md, website/_data/doclinks.yml, website/documentation/appendix/datatype-dsl-reference.md, website/documentation/appendix/functionblock-dsl-reference.md, website/documentation/appendix/informationmodel-dsl-reference.md, website/documentation/appendix/mappingmodel-dsl-reference.md
@MichaelGuenther Here's the branch for this documentation task.
=> Fixes #253 - Update DSL Grammar.

server/docker-compose-build.yml, server/docker-compose.yml
=> remove leshan code generator configuration in docker compose;

website/blog/2016-09-13-blogboschconnect.md
=> Included blog post on Vorto in BoschConnect.

bundles/org.eclipse.vorto.codegen/src/org/eclipse/vorto/codegen/api/InvocationContext.java
Signed-off-by: Jeroen Laverman <jeroen.laverman@bosch-si.com>
=> Extend getMappedElement() function to consider Entities and Enums. Fixes #386

example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/JsonschemaGenerator.java, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/Utils.xtend, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/ConfigurationValidationTask.java, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/FaultValidationTask.java, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/StatusValidationTask.java, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/template/ConfigurationValidationTemplate.xtend, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/template/FaultValidationTemplate.xtend, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/tasks/template/StatusValidationTemplate.xtend
Json Schema Generator for all fb elements. Fixes #421
=> Json Schema Generator for all fb elements. Fixes #421

server/devtool/pom.xml, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/DevToolServer.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/controller/ProjectController.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/controller/editor/DatatypeEditorController.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/controller/editor/FunctionBlockEditorController.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/controller/editor/InformationModelEditorController.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/controller/publisher/PublisherController.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/models/ProjectResourceListWrapper.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/service/impl/editor/DatatypeEditorServiceImpl.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/service/impl/editor/FunctionBlockEditorServiceImpl.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/service/impl/editor/InformationModelEditorServiceImpl.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/utils/Constants.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/utils/DevtoolReferenceLinker.java, server/devtool/src/main/java/org/eclipse/vorto/server/devtool/utils/DevtoolRestClient.java, server/devtool/src/main/resources/application.properties, server/devtool/src/main/resources/static/css/style.css, server/devtool/src/main/resources/static/dist/js/controllers.js, server/devtool/src/main/resources/static/dist/js/devtoolApp.js, server/devtool/src/main/resources/static/templates/editor-template.html, server/devtool/src/main/resources/static/templates/project-template.html, server/devtool/src/main/resources/static/templates/publish-template.html, server/repo/repo-http-models/pom.xml, server/repo/repo-http-models/src/main/java/org/eclipse/vorto/http/model/ServerResponse.java, server/repo/repo-ui/src/main/java/org/eclipse/vorto/repository/web/ShareModelController.java
=> Fixes #406

website/blog/2016-11-15-vorto-web-modeler.md
Signed-off-by: Srinivasan Deepalakshmi Venkatachary (INST/ESW2-Sgp) <deepalakshmi.srinivasan@bosch-si.com>
=> New blog post on Vorto Web Modeler

server/devtool/src/main/resources/static/dist/js/controllers.js, server/devtool/src/main/resources/static/templates/editor-template.html
=> Fix for #429

server/devtool/src/main/java/org/eclipse/vorto/server/devtool/service/impl/editor/InformationModelEditorServiceImpl.java, server/devtool/src/main/resources/static/dist/js/controllers.js, server/devtool/src/main/resources/static/templates/editor-template.html
=> Fix for #430

bundles/org.eclipse.vorto.core.ui/META-INF/MANIFEST.MF, bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/DefaultMessageDisplay.java, bundles/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/IMessageDisplay.java, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/dropaction/RepositoryResourceDropAction.java, bundles/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/dropvalidator/TargetClassModelTypeValidator.java
=> Fix for https://github.com/eclipse/vorto/issues/440

bundles/org.eclipse.vorto.codegen.ui/src/org/eclipse/vorto/codegen/ui/handler/CodeGeneratorInvocationHandler.java, example-generators/org.eclipse.vorto.codegen.examples.jsonschema/src/org/eclipse/vorto/codegen/examples/jsonschema/JsonschemaGenerator.java
=> Fixes #441

example-generators/org.eclipse.vorto.codegen.examples.lwm2m/src/org/eclipse/vorto/codegen/examples/lwm2m/templates/FunctionBlockXmlTemplate.java
=> Use the resourceIdSet's size to initialize ID of items. Fixes #442

bundles/org.eclipse.vorto.repository/src/org/eclipse/vorto/repository/RestModelRepository.java, server/generators/org.eclipse.vorto.codegen.service.prosystfi/pom.xml, server/pom.xml, server/repo/repo-ui/src/main/java/org/eclipse/vorto/repository/web/ModelGenerationController.java
=> Fixes #449 - https://github.com/eclipse/vorto/issues/449

server/generators/org.eclipse.vorto.codegen.service.prosystfi/src/main/resources/application.properties
=> Shorten Prosyst FI generator name to Prosyst.

bundles/org.eclipse.vorto.codegen/src/org/eclipse/vorto/codegen/api/GeneratorServiceInfo.java, server/generators/org.eclipse.vorto.codegen.service.prosystfi/src/main/resources/application.properties, server/generators/org.eclipse.vorto.codegen.service/src/main/java/org/eclipse/vorto/service/generator/web/CodeGenerationController.java, server/repo/repo-core/src/main/java/org/eclipse/vorto/repository/model/GeneratorServiceInfo.java, server/repo/repo-ui/src/main/java/org/eclipse/vorto/repository/web/ModelGenerationController.java
- Add tags to generator info
- Modify API to allow ordering by tags. Empty orderBy defaults to "production" tag.
=> Feature/vorto 454 - https://github.com/eclipse/vorto/issues/454

server/generators/org.eclipse.vorto.codegen.service.bosch.things/src/main/resources/application.properties, server/generators/org.eclipse.vorto.codegen.service.prosystfi/pom.xml, server/generators/org.eclipse.vorto.codegen.service.prosystfi/src/main/resources/application.properties
Documentation Links, tags property for [things generator ](https://github.com/eclipse/vorto/issues/454#issuecomment-264082407) and typo fix.
=> Documentation Links, tags property for things generator and typo

pom.xml
=> Fixes #80. Automated deployment to maven central.

pom.xml
=> Bumped up the version of maven-gpg-plugin

pom.xml
=> Bump up the version of javadoc plugin

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/ModelGenerationController.java
=> Extract specific file from generated output using ! notation. Fixes #489

server/repo/repository-api/src/main/java/org/eclipse/vorto/repository/api/ModelQueryBuilder.java, server/repo/repository-api/src/main/java/org/eclipse/vorto/repository/api/exception/ModelQueryException.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/ModelRepositoryController.java
=> Encode and decode query parameters for search.

server/pom.xml
=> Add plugin repo for eclipse CBI releases

maven/pom.xml, server/pom.xml
Added license, scm, developer information, and javadoc profile for server pom.xml
=> Added license, scm, developer information, and javadoc profile

server/repo/repository-api/src/main/java/org/eclipse/vorto/repository/api/IModelRepository.java, server/repo/repository-server/pom.xml, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/internal/service/IModelParser.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/internal/service/ITemporaryStorage.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/internal/service/generation/IGeneratorLookupRepository.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/internal/service/utils/ModelIdHelper.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/internal/service/utils/ModelSearchUtil.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/model/IModelContent.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/service/IGeneratorService.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/service/IModelRepository.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/service/IRepositoryManager.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/service/IUserRepository.java
=> Fix javadoc problems in build.

maven/pom.xml
=> Add plugin repo of eclipse to maven plugin project

cli/command/info.go, cli/models/model.go, cli/models/vortotime.go
=> Modify model to use time.Time instead of int64

bundles/org.eclipse.vorto.perspective.vorto/src/org/eclipse/vorto/perspective/vorto/dnd/dropvalidation/DatatypeValidator.java, framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/dropvalidator/TargetClassModelTypeValidator.java
=> Fixes #511 - Drag and Drop of enum within enum should be restricted

bundles/org.eclipse.vorto.wizard.vorto/src/org/eclipse/vorto/wizard/datatype/DatatypeWizardPage.java, bundles/org.eclipse.vorto.wizard.vorto/src/org/eclipse/vorto/wizard/functionblock/FunctionBlockWizardPage.java, bundles/org.eclipse.vorto.wizard.vorto/src/org/eclipse/vorto/wizard/infomodel/InfomodelWizardPage.java, bundles/org.eclipse.vorto.wizard.vorto/src/org/eclipse/vorto/wizard/mapping/MappingModellWizardPage.java, framework/org.eclipse.vorto.wizard/src/org/eclipse/vorto/wizard/ModelBaseWizardPage.java
=> Fixes #516 - Duplicate model validation is not handled.

website/blog/2017-03-24-krishi-iot-solution.md, website/news/2017-03-23-newsLetter.md
Signed-off-by: deepagithub <deepalakshmi.srinivasan@bosch-si.com>
=> Newsletter and blogpost

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/config/RepositoryConfigurationLocal.java
=> removed duplicate encoding in password. Fixes #DX-503

server/generators/gateway/src/main/java/org/eclipse/vorto/codegen/gateway/GatewayInit.java, server/generators/gateway/src/main/java/org/eclipse/vorto/codegen/gateway/service/VortoService.java, server/generators/gateway/src/main/java/org/eclipse/vorto/codegen/gateway/utils/GatewayUtils.java
=> Enable externalization of generator images

server/generators/gateway/src/main/java/org/eclipse/vorto/codegen/gateway/service/VortoService.java
=> Make error log more informative by giving it the stracktrace

server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/utils/DevtoolReferenceLinker.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/ProjectController.java, server/devtool/webeditor/src/main/resources/static/css/style.css, server/devtool/webeditor/src/main/resources/static/dist/js/controllers.js, server/devtool/webeditor/src/main/resources/static/index.html, server/devtool/webeditor/src/main/resources/static/templates/add-editor-modal-template.html, server/devtool/webeditor/src/main/resources/static/templates/create-project-modal-template.html, server/devtool/webeditor/src/main/resources/static/templates/describe-editor-modal-template.html, server/devtool/webeditor/src/main/resources/static/templates/project-template.html
=> Improved project view interface

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/security/AuthorizationTokenFilter.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/security/InterceptedUserInfoTokenServices.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/security/SecurityConfiguration.java
=> Allow github bearer token authorization for secured REST apis

generators/org.eclipse.vorto.codegen.lwm2m/src/org/eclipse/vorto/codegen/lwm2m/LWM2MGenerator.java
=> XML gererator is commentted out in LWM2M generator. Fixes #575

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/internal/service/signup/DefaultRegistrationService.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/identity/UserController.java, server/repo/repository-server/src/main/resources/static/partials/settings-template.html
=> Fix for the user settings bug.

server/repo/repository-server/src/main/resources/static/css/style.css, server/repo/repository-server/src/main/resources/static/index.html
=> updated the top banner text to Eclipse Vorto Repository

server/repo/repository-server/src/main/resources/static/js/controllers.js
=> Fix bug in discussion section of model details.

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/security/eidp/EidpOAuth2RestTemplate.java
=> Use bosch style in EIDP SSO login

server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/EditorController.js, server/devtool/webeditor/src/main/resources/static/templates/editor/editor-template.html
=> Displaying loader while validating files

server/devtool/webeditor/Readme.md
=> Added Readme.md for Vorto devtool

generators/org.eclipse.vorto.codegen.bosch.things/src/org/eclipse/vorto/codegen/bosch/things/alexa/AlexaThingsTask.java, generators/org.eclipse.vorto.codegen.bosch.things/src/org/eclipse/vorto/codegen/bosch/things/alexa/templates/AbstractAlexaTemplate.xtend, generators/org.eclipse.vorto.codegen.bosch.things/src/org/eclipse/vorto/codegen/bosch/things/alexa/templates/AlexaIndentSchemaTemplate.xtend, generators/org.eclipse.vorto.codegen.bosch.things/src/org/eclipse/vorto/codegen/bosch/things/alexa/templates/AlexaSkillLambdaTemplate.xtend, generators/org.eclipse.vorto.codegen.bosch.things/src/org/eclipse/vorto/codegen/bosch/things/alexa/templates/AlexaSlotTypeTemplate.xtend, generators/org.eclipse.vorto.codegen.bosch.things/src/org/eclipse/vorto/codegen/bosch/things/alexa/templates/AlexaUtterancesTemplate.xtend, server/repo/repository-server/src/main/resources/static/js/controllers.js
=> Add ability to generate alexa artifacts to Things Generator

generators/org.eclipse.vorto.codegen.bosch.things/src/org/eclipse/vorto/codegen/bosch/things/BoschIoTThingsGenerator.java
=> Add alexa to list of task of Things generator

tests/jmeterTests/PerformanceTest_ThingRepo.jmx, tests/jmeterTests/PlatformData_Thing.csv, tests/jmeterTests/pom.xml
Signed-off-by: deepagithub <deepalakshmi.srinivasan@bosch-si.com>
=> Included JMeter Script, Data and Pom file. Fixes DX-512.

server/devtool/webeditor/Readme.md
=> Updated Readme.md for Vorto Web Editor

server/devtool/projectrepository-file/src/main/java/org/eclipse/vorto/devtool/projectrepository/file/ProjectRepositoryFileConstants.java, server/devtool/projectrepository-file/src/main/java/org/eclipse/vorto/devtool/projectrepository/file/ProjectRepositoryServiceFS.java, server/devtool/projectrepository-file/src/main/java/org/eclipse/vorto/devtool/projectrepository/file/ResourceQueryFS.java, server/devtool/projectrepository-file/src/test/java/org/eclipse/vorto/devtool/projectrepository/ProjectRepositoryFSTest.java, server/devtool/webeditor/Readme.md, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/config/XtextConfiguration.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/service/impl/XtextEditorProjectServiceImpl.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/utils/WebUtils.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/ProjectController.java
=> Fixes #597

server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/CloseEditorController.js, server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/EditorController.js
=> Fixes #613

server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/EditorController.js
=> Fixes #617

server/devtool/org.eclipse.vorto.editor.web/src/main/java/org/eclipse/vorto/editor/web/resource/FileResourceHandler.xtend, server/devtool/projectrepository-api/src/main/java/org/eclipse/vorto/devtool/projectrepository/IProjectRepositoryService.java, server/devtool/projectrepository-file/src/main/java/org/eclipse/vorto/devtool/projectrepository/file/ProjectRepositoryFileConstants.java, server/devtool/projectrepository-file/src/main/java/org/eclipse/vorto/devtool/projectrepository/file/ProjectRepositoryServiceFS.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/config/EditorConfigurationCloud.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/config/EditorConfigurationLocal.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/http/request/DeleteResourceRequest.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/http/request/LinkReferenceModelRequest.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/http/request/LinkReferenceResourceRequest.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/http/response/Response.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/models/GlobalContext.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/models/LinkReferenceResponse.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/service/IEditorService.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/service/IProjectService.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/service/impl/XtextEditorProjectServiceImpl.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/utils/Constants.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/utils/DevtoolReferenceLinker.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/utils/WebUtils.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/ProjectController.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/editor/AbstractEditorController.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/editor/DatatypeEditorController.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/editor/FunctionBlockEditorController.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/editor/InformationModelEditorController.java, server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/EditorController.js
=> Fixes #625

server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/EditorController.js
=> Fixes  #628

server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/service/IProjectService.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/service/impl/XtextEditorProjectServiceImpl.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/ProjectController.java, server/devtool/webeditor/src/main/resources/static/dist/js/controllers/init/AppControllerLoader.js, server/devtool/webeditor/src/main/resources/static/dist/js/controllers/project/DeleteProjectController.js, server/devtool/webeditor/src/main/resources/static/dist/js/controllers/project/ProjectController.js, server/devtool/webeditor/src/main/resources/static/dist/js/services/common/ShareDataService.js, server/devtool/webeditor/src/main/resources/static/dist/js/services/data/project/ProjectDataService.js, server/devtool/webeditor/src/main/resources/static/templates/editor/editor-template.html, server/devtool/webeditor/src/main/resources/static/templates/project/delete-project-modal-template.html, server/devtool/webeditor/src/main/resources/static/templates/project/project-template.html
=> Added feature to delete a project

server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/EditorController.js
=> Added additional hints for the web editor

server/devtool/webeditor/src/main/resources/application-local.yml, server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/EditorController.js, server/devtool/webeditor/src/main/resources/static/dist/js/controllers/project/ProjectController.js, server/devtool/webeditor/src/main/resources/static/templates/editor/editor-template.html, server/devtool/webeditor/src/main/resources/static/templates/project/project-template.html
=> Displaying loader on front end while the file explorer is being rendered

server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/EditorController.js
=> Fixes #645

server/devtool/webeditor/src/main/resources/static/dist/js/controllers/editor/EditorController.js
=> Fixes #648

server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/utils/WebUtils.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/ProjectController.java
=> Fixes #650

bundles/org.eclipse.vorto.perspective.vorto/src/org/eclipse/vorto/perspective/vorto/dnd/dropvalidation/DatatypeValidator.java, framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/dropvalidator/TargetClassModelTypeValidator.java
Fixes #624 - Error when Drag and Drop a Datatype to Project
=> Fixes #624 - https://github.com/eclipse/vorto/issues/624

bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/validation/FunctionblockValidator.xtend, framework/org.eclipse.vorto.core.ui/src/org/eclipse/vorto/core/ui/DefaultMessageDisplay.java, framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/command/ShareModelAction.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/internal/service/JcrModelRepository.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/internal/service/validation/TypeImportValidation.java, server/repo/repository-server/src/main/resources/static/js/app.js, server/repo/repository-server/src/main/resources/static/partials/settings-template.html, server/repo/repository-server/src/main/resources/static/partials/signup-template.html
Add reference import validation, ix 623, and fix signup when username is not in email form
=> Add reference import validation, fix 623, and fix signup when username is not in email form

server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/utils/WebUtils.java, server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/ProjectController.java
=> Fixes #657

generators/org.eclipse.vorto.codegen.aws/plugin.xml, generators/org.eclipse.vorto.codegen.markdown/plugin.xml, generators/org.eclipse.vorto.codegen.thingworx/plugin.xml
=> Fixes #672 - https://github.com/eclipse/vorto/issues/672

framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/AbstractProjectSelectionViewPart.java
=> Fixes #677 - https://github.com/eclipse/vorto/issues/677

cli/command/share.go, cli/models/response.go
=> Fixes #682 - CLI error when sharing.

website/_layouts/downloads.html
Signed-off-by: deepagithub <deepalakshmi.srinivasan@bosch-si.com>
=> Updated the download link of nightly zip to point to 0.10.0-M1.zip

framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/dropaction/AddSharedReferenceDropAction.java, framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/dropvalidator/TargetClassModelTypeValidator.java
If a user drops "Model A" from the Repository to any "Model B", "Model A" is ADDED to the project (copied from the Repo). A Reference (using ...) to "Model A" is also added to "Model B" if it legally makes sense.
=> Fixes #666

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/HomeController.java, server/repo/repository-server/src/main/resources/static/index.html, server/repo/repository-server/src/main/resources/static/js/controllers.js
=> Fixes #669 - First time Sign-up page shows 'Share' menu item

framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/dnd/dropaction/AddSharedReferenceDropAction.java, framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/ModelUploadDialog.java
=> Check for nulls.

server/devtool/webeditor/src/main/java/org/eclipse/vorto/server/devtool/web/controller/publisher/PublisherController.java
=> Fixes #696

website/blog/2017-07-21-rapid-iot-prototyping.md
Signed-off-by: deepagithub <deepalakshmi.srinivasan@bosch-si.com>
=> Included a blog post on Rapid IoT Prototyping

framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/listener/RemoveImportListener.java, framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/listener/ResourceListenerException.java, framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/util/Predicates.java, framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/view/AbstractProjectSelectionViewPart.java
=> Fixes #667 - Removing an imported model does not refresh tree

tutorials/tutorial_connect_xdk_ble.md
=> Modified to take advantage of maven dependency resolution mechanism.

generators/org.eclipse.vorto.codegen.kura/src/org/eclipse/vorto/codegen/kura/KuraGenerator.java, generators/org.eclipse.vorto.codegen.kura/src/org/eclipse/vorto/codegen/kura/templates/PomTemplate.xtend
=> Fixes #719 - Kura Generator generates pom.xml

features/org.eclipse.vorto.feature.generators/feature.xml, generators/pom.xml
=> removed references to mqtt.python for testing Hudson build

server/devtool/webeditor/Readme.md
=> Updated Readme.md of webeditor for modeshape related changes

server/repo/repository-mapping/src/main/java/org/eclipse/vorto/service/mapping/converters/JavascriptEvalFunction.java
=> Changed unwrapping of function parameters

tutorials/Readme.md, tutorials/tutorial_connect_device_using_mqtt_python.md
=> tutorial for connect a device using mqtt python generator

server/repo/repository-mapping/Readme.md, server/repo/repository-mapping/src/main/java/org/eclipse/vorto/service/mapping/BleGattCharacteristic.java, server/repo/repository-mapping/src/main/java/org/eclipse/vorto/service/mapping/BleGattDevice.java, server/repo/repository-mapping/src/main/java/org/eclipse/vorto/service/mapping/BleGattDeviceBuilder.java, server/repo/repository-mapping/src/main/java/org/eclipse/vorto/service/mapping/BleGattInitSequenceElement.java, server/repo/repository-mapping/src/main/java/org/eclipse/vorto/service/mapping/BleGattService.java, server/repo/repository-mapping/src/test/java/org/eclipse/vorto/service/mapping/BleGattMappingTest.java
=> Added an object model for BLE GATT devices

server/repo/repository-mapping/src/main/java/org/eclipse/vorto/service/mapping/BleGattCharacteristic.java, server/repo/repository-mapping/src/main/java/org/eclipse/vorto/service/mapping/BleGattDeviceBuilder.java, server/repo/repository-mapping/src/main/java/org/eclipse/vorto/service/mapping/spec/RemoteMappingSpecification.java, server/repo/repository-mapping/src/test/java/org/eclipse/vorto/service/mapping/BleGattMappingTest.java
for unmapped functionblocks
- Corresponding changes in BLE functionality by checking for
targetplatform == "blegatt"
Apologies for the diff formatting of the crucial pieces
=> - Allow for partial mapping of function blocks, targetplatform is null

framework/org.eclipse.vorto.codegen/src/org/eclipse/vorto/codegen/api/InvocationContext.java
=> Changed match for functionblock property to deep match to include

server/devtool/webeditor/src/main/resources/static/templates/editor/editor-template.html
=> Disabled editor validation toggle

server/repo/repository-server/src/main/resources/vorto-repository-config-h2.json
=> Fixes #785

generators/org.eclipse.vorto.codegen.artik/src/org/eclipse/vorto/codegen/artik/templates/DeviceManifestTemplate.xtend
Signed-off-by: Yuvaraj <yuvarajsripathi91@gmail.com>
=> Fix ARTIK cloud manifest validation errors

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/core/ModelRepositoryController.java, server/repo/repository-web/src/main/resources/static/partials/details-template.html
=> Uploading of model images can only be done by authorized users.

server/repo/repository-web/src/main/resources/application.properties
See: [Stackoverflow](https://stackoverflow.com/questions/36386462/multipart-file-exceed-limit-exception/36386563#36386563) and [Spring Book Guide - Uploading Files](https://spring.io/guides/gs/uploading-files/)
=> The property to change max file size for an upload has changed in Spring Boot

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/backup/BackupController.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/core/ModelRepositoryController.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/core/ShareModelController.java, server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/core/exceptions/UploadTooLargeException.java, server/repo/repository-web/src/main/resources/application-local.yml, server/repo/repository-web/src/main/resources/application.properties
=> Limit the maximum filesizes of uploads to prevent DOS attacks.

generators/org.eclipse.vorto.codegen.thingworx/about.html
=> Fixes #810 updated thingworx generators about page

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/web/comment/CommentController.java
=> Check if user is logged in before he can comment.

website/_config.yml, website/_layouts/blog_summary.html, website/documentation/developer-api/using-mapping-model.md
=> updated _config, blog_summary and other to get build with Jekyll 3.5

generators/org.eclipse.vorto.codegen.bosch.things/src/org/eclipse/vorto/codegen/bosch/things/javaclient/templates/ThingsClientTemplate.xtend
=> Make simulated data conform with current Ditto structure.

generators/org.eclipse.vorto.codegen.mqtt.python/src/org/eclipse/vorto/codegen/mqtt/python/PythonDittoSerializerTemplate.xtend
=> Make python generator conform with Ditto new structure.

generators/org.eclipse.vorto.codegen.arduino/src/org/eclipse/vorto/codegen/arduino/ArduinoFbSourceTemplate.xtend
=> Make arduino generator conform with Ditto structure

generators/org.eclipse.vorto.codegen.kura/src/org/eclipse/vorto/codegen/kura/templates/cloud/bosch/BoschDataServiceTemplate.xtend, generators/org.eclipse.vorto.codegen.kura/src/org/eclipse/vorto/codegen/kura/templates/cloud/bosch/BoschHubDataService.xtend
=> Adapt kura generator to new Ditto structure

tutorials/tutorial_connect_xdk_ble.md, tutorials/tutorial_create_webapp_dashboard.md
=> Fixes broken link in tutorials

generators/org.eclipse.vorto.codegen.arduino/src/org/eclipse/vorto/codegen/arduino/ArduinoFbSourceTemplate.xtend
=> Fixes #832 removes StringString

generators/org.eclipse.vorto.codegen.aws/src/org/eclipse/vorto/codegen/aws/alexa/templates/AlexaSkillLambdaTemplate.xtend
=> updated alexa skillset template

generators/org.eclipse.vorto.codegen.arduino/src/org/eclipse/vorto/codegen/arduino/ArduinoFbHeaderTemplate.xtend, generators/org.eclipse.vorto.codegen.arduino/src/org/eclipse/vorto/codegen/arduino/ArduinoFbSourceTemplate.xtend, generators/org.eclipse.vorto.codegen.arduino/src/org/eclipse/vorto/codegen/arduino/ArduinoImHeaderTemplate.xtend, generators/org.eclipse.vorto.codegen.arduino/src/org/eclipse/vorto/codegen/arduino/ArduinoImSourceTemplate.xtend, generators/org.eclipse.vorto.codegen.arduino/src/org/eclipse/vorto/codegen/arduino/ArduinoSketchTemplate.xtend
=> Added namespace to class names

generators/org.eclipse.vorto.codegen.ditto/src/org/eclipse/vorto/codegen/ditto/schema/SchemaValidatorTask.java, generators/org.eclipse.vorto.codegen.ditto/src/org/eclipse/vorto/codegen/ditto/schema/tasks/ValidationTaskFactory.java, generators/org.eclipse.vorto.codegen.ditto/src/org/eclipse/vorto/codegen/ditto/schema/tasks/template/PropertiesConfigurationValidationTemplate.xtend, generators/org.eclipse.vorto.codegen.ditto/src/org/eclipse/vorto/codegen/ditto/schema/tasks/template/PropertiesSinglePropertyValidationTemplate.xtend, generators/org.eclipse.vorto.codegen.ditto/src/org/eclipse/vorto/codegen/ditto/schema/tasks/template/PropertiesValidationTemplate.xtend
instead of 'configuration' as object in Feature properties.
the generated JSON schema should be aligned to what Vorto defines in its FB model - otherwise one will make errors using that.
=> fixed that Ditto JSON schema generator used 'config'

server/repo/repository-server/src/main/java/org/eclipse/vorto/repository/backup/impl/DefaultModelBackupService.java
=> Fixes restore backup model data

server/repo/repository-web/src/main/java/org/eclipse/vorto/repository/web/config/RepositoryConfiguration.java, server/repo/repository-web/src/main/resources/static/partials/signup-template.html
Since we take the username from the OAuth provider and use it as key in the application, make it read-only and remove the pattern test.
=> Hyphen in username

generators/org.eclipse.vorto.codegen.ditto/src/org/eclipse/vorto/codegen/ditto/schema/tasks/template/PropertiesValidationTemplate.xtend
Forgot that when changing "config" to "configuration".
=> Fixed "required" section in generated JsonSchema in Ditto generator

server/generators/org.eclipse.vorto.codegen.service.gateway/src/main/resources/generators/bosch-things.properties
=> Fixes #867 documentation link for the Bosch IoT Suite

website/_config-prod.yml, website/_includes/base.html
=> added prod config.yml and updated base.html for fix links

website/_includes/base.html
=> updated base property to /vorto

bundles/org.eclipse.vorto.editor.functionblock/src/org/eclipse/vorto/editor/functionblock/Functionblock.xtext, framework/org.eclipse.vorto.core/model/Functionblock.ecore
This fixes #907. Added constraints also to object type.
=> Added Dictionary to operations as parameter and return type

bundles/org.eclipse.vorto.editor.infomodel.ide/META-INF/MANIFEST.MF, bundles/org.eclipse.vorto.editor.infomodel.ui/META-INF/MANIFEST.MF, bundles/org.eclipse.vorto.editor.infomodel/META-INF/MANIFEST.MF, bundles/org.eclipse.vorto.editor.infomodel/src/org/eclipse/vorto/editor/infomodel/InformationModel.xtext, bundles/org.eclipse.vorto.editor.infomodel/src/org/eclipse/vorto/editor/infomodel/formatting/InformationModelFormatter.xtend, framework/org.eclipse.vorto.core/model/InformationModel.ecore
As discussed in #153 a device does not necessarily need to implement all functionblocks.
=> Fixes #153 - Added presence modifier to information model functionblocks

server/repo/repository-web/src/main/resources/static/partials/upload-template.html
=> Add a note saying uploaded model can be viewed by other users in Vorto

cli/command/config.go, cli/command/help.go
Signed-off-by: Syam Sasidharan <syam.sasidharan@bosch-si.com>
=> Fixing the issues with cli tool to make it gdpr compliant. #1417

framework/org.eclipse.vorto.perspective/src/org/eclipse/vorto/perspective/command/ShareModelAction.java
=> Minor cosmetic changes on the Share Dialog

repository-api/src/main/java/org/eclipse/vorto/repository/api/ModelInfo.java, repository-api/src/main/java/org/eclipse/vorto/repository/api/ModelType.java, repository-api/src/main/java/org/eclipse/vorto/repository/api/upload/StagingResult.java, repository-api/src/main/java/org/eclipse/vorto/repository/api/upload/UploadModelResponse.java, repository-java-client/pom.xml, repository/pom.xml, repository/repository-generators/pom.xml, repository/repository-server/src/main/java/org/eclipse/vorto/repository/core/IModelRepository.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/core/impl/JcrModelRepository.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/core/impl/utils/ModelSearchUtil.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/CommittedModel.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/IModelImporter.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/ModelImporterException.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/ModelImporterService.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/impl/AbstractModelImporter.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/impl/vorto/VortoModelImporter.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/impl/vorto/VortoStagingDetails.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/web/core/ModelDtoFactory.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/web/core/ShareModelController.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/workflow/IWorkflowService.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/workflow/impl/DefaultWorkflowService.java, repository/repository-web/src/main/resources/static/js/controllers.js, repository/repository-web/src/main/resources/static/partials/upload-template.html
=> First draft of import framework

repository/repository-server/src/main/java/org/eclipse/vorto/repository/web/core/ModelRepositoryController.java, repository/repository-web/src/main/java/org/eclipse/vorto/repository/web/config/MethodSecurityConfig.java
=> Add a way to configure search to be for authenticated users only.

repository/repository-generators/pom.xml
Signed-off-by: emantos <erleczar.mantos@bosch-si.com>
=> Fix generator dependencies.

repository/repository-server/src/main/java/org/eclipse/vorto/repository/core/IModelRepository.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/core/impl/JcrModelRepository.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/web/attachment/AttachmentController.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/core/ModelRepositoryAttachmentTest.java
=> Add backend functionality for deleting attachments

repository/repository-api/src/main/java/org/eclipse/vorto/repository/api/ModelInfo.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/core/IModelRepository.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/core/impl/JcrModelRepository.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/AbstractModelImporter.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/web/core/ModelDtoFactory.java, repository/repository-server/src/main/resources/sequencer-model.cnd, repository/repository-server/src/test/resources/sequencer-model.cnd
=> Add an imported flag on a model that's imported.

repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/impl/VortoModelImporter.java
=> Fix error when zip file has unsupported files causing a parser error

repository/repository-web/src/main/resources/application-local.yml, repository/repository-web/src/main/resources/static/index.html, repository/repository-web/src/main/resources/static/js/app.js, repository/repository-web/src/main/resources/static/js/controllers/controller.js, repository/repository-web/src/main/resources/static/js/controllers/signUpController.js
=> Modified the frontend to use the authenticatedSearchMode flag.

repository/repository-server/src/main/java/org/eclipse/vorto/repository/web/AngularCsrfHeaderFilter.java
=> rewrote the code for the java class

repository/repository-server/src/main/java/org/eclipse/vorto/repository/account/impl/DefaultUserAccountService.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/account/UserAccountServiceTest.java
=> Anonymize models of deleted users

repository/repository-server/src/main/java/org/eclipse/vorto/repository/comment/ICommentService.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/comment/impl/CommentRepository.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/comment/impl/DefaultCommentService.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/upgrade/impl/AbstractUserUpgradeTask.java, repository/repository-server/src/main/java/org/eclipse/vorto/repository/upgrade/impl/CommentAuthorUnhashUpgradeTask.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/upgrade/CommentAuthorUnhashUpgradeTaskTest.java
=> User upgrade task for unhashing the author of comments

repository/repository-server/src/main/java/org/eclipse/vorto/repository/importer/AbstractModelImporter.java
This is a temporary fix for the IPSO model import problem while we are trying to determine its root cause.
=> Temporary fix for the IPSO model import

website/content/tutorials/payloadmapping.md
=> payloadmapping file updated

repository/repository-server/src/main/java/org/eclipse/vorto/repository/sso/AuthorizationTokenFilter.java
=> Log and return a 401 when an invalid access token is detected.

repository/repository-web/src/main/resources/static/css/style.css, repository/repository-web/src/main/resources/static/partials/details-template.html
=> updated the code in style.css file. Fixes #1048

repository/repository-server/src/main/java/org/eclipse/vorto/repository/init/AddTechnicalUserInit.java
=> Correct way to initialize a @Value to an empty string array

repository/pom.xml
=> updated tomcat-embed-websocket from 8.5.31 to 8.5.32

client/pom.xml, core-bundles/generators/pom.xml, pom.xml, repository/pom.xml, repository/repository-importer/pom.xml, utilities/pom.xml
=> pom.xml files updated

repository/repository-server/src/main/java/org/eclipse/vorto/repository/web/TenantVerificationFilter.java, repository/repository-web/src/main/resources/static/js/controllers/mapping/mappingbuilder-controller.js
- Return 403 forbidden if JWT token and tenantId in URL doesn't agree.
- Don't include the error message in the return value to user (for security reasons)
=> Return 403 forbidden if JWT token and tenantId in URL doesn't agree.

repository/migration/migrate_db_2018_11_09.sql
=> Add migration script two add a user_role table and do the user transformation

plugin-sdk/Readme.md, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/CodeGeneratorTemplateGenerator.java, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/parent/PomTemplate.xtend, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/plugin/GeneratorMainTemplate.xtend, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/plugin/HelloWorldTemplate.xtend, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/plugin/PomTemplate.xtend, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/runner/DockerComposeTemplate.xtend, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/runner/DockerRunGeneratorsShTemplate.xtend, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/runner/DockerWaitForItShTemplate.xtend, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/runner/GeneratorConfigurationTemplate.xtend, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/runner/PomTemplate.xtend
=> Fix issues with the template generator

generators/generator-runner/src/main/resources/generators/generator_template.properties
=> Fixes #1168, documentation link updated

generators/pom.xml
=> added spotify plugin cfg for generators

repository/repository-server/src/main/resources/application.properties
=> included json file type to the list of attachments that can be uploaded

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/IDiagnostics.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/JcrModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/AbstractRepositoryController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/core/ModelRepositoryController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/core/PayloadMappingController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/diagnostics/DiagnosticsController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/generation/GeneratorController.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/ModelRepositoryDiagnosticsTest.java, repository/repository-web/dist/js/controllers/detailsController.js, repository/repository-web/dist/js/controllers/mapping/mappingbuilder-controller.js, repository/repository-web/dist/partials/admin-template.html, repository/repository-web/dist/partials/details-template.html, repository/repository-web/dist/partials/mapping/mappingcreator.html
=> Fixes #1181

repository/repository-web/dist/partials/details-template.html, repository/repository-web/dist/partials/search-template.html, repository/repository-web/dist/partials/templates/pagination.custom.html
=> Added better pagination fixes #1094

repository/repository-web/dist/partials/templates/pagination.custom.html
=> Fixes #1203, pagination is handled on the lastpage

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/core/PayloadMappingController.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/MappingTest.java, repository/repository-core/src/test/resources/mappingRequest.json
=> Fixes #1172 - Model Instance data Validation fails at Integer properties

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/validation/TypeImportValidation.java
=> Fixes #1179 - allow keywords contained in the property name, op name

website/content/userguide/generators.md
=> Fixes #1216, failure link is updated

repository/repository-server/pom.xml, repository/repository-server/src/main/test/AttachmentsControllerIntegrationTest.java, repository/repository-server/src/main/test/GeneratorsControllerIntegrationTest.java, repository/repository-server/src/main/test/ModelControllerIntegrationTest.java, repository/repository-server/src/main/test/ModelSearchControllerIntegrationTest.java, repository/repository-server/src/main/test/TestModel.java
=> Add integration tests

website/content/userguide/quickhelp_dsl.md
=> Fixes #1180

.travis.yml, generators/generator-runner/pom.xml, model/src/main/java/org/eclipse/vorto/model/DictionaryType.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/sso/TokenUtils.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/core/ModelDtoFactory.java, repository/repository-server-config/src/main/java/org/eclipse/vorto/repository/server/config/config/RepositoryConfiguration.java, repository/repository-server/Dockerfile
Also adds the possibility to only set proxy url and port
=> fixes #1213

.travis.yml
=> Fix indent for travis ci yml

repository/docker-compose.yml
=> Remove example generators

mapping-engine/mapping-core/src/test/java/org/eclipse/vorto/mapping/engine/model/binary/BinaryDataTest.java, model-runtime/src/test/java/org/eclipse/vorto/model/BooleanAttributePropertyTest.java, pom.xml, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/account/AccountController.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/it/AbstractIntegrationTest.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/web/account/AccountControllerTest.java, sonar-project.properties
=> Add Tests to increase converage

utilities/Readme.md
=> Modification to the modelworkspace reader tutorial.

docs/tutorials/connect_javadevice.md
=> Change the tutorial to reflect current situation

docker/Repository_Dockerfile, docker/scripts/run.py
Add sideloading for Dockerfiles
=> Remove mariadb from pom.xml

.gitignore, .travis.yml, docker-compose-build.yml, docker-compose.yml, docker/Generators_Dockerfile, docker/Repository_Dockerfile, docker/config/3rd-party-generators/Readme.md, docker/config/generators/Readme.md, docker/config/repository/Readme.md, docker/scripts/run.py, docker/vorto-variables.env, generators/generator-runner/src/main/resources/application-cloud.yml, generators/generator-runner/src/main/resources/application-eclipse.yml, generators/generator-runner/src/main/resources/application.properties, generators/generator-runner/src/main/resources/application.yml, repository/repository-server-config/src/main/java/org/eclipse/vorto/repository/server/config/config/SwaggerConfiguration.java, repository/repository-server/pom.xml, repository/repository-server/src/main/resources/application-eclipse.yml, repository/repository-server/src/main/resources/application.yml, repository/repository-server/src/main/resources/static/index.html, repository/repository-server/src/main/resources/vorto-repository-config-mysql.json
* Fix Docker options
* Fixing docker
* Add variables to gitignore
* Add docker images for eclipse rollout
* Add default value for active profile
* Increase repository timeout to 120 to allow for setup
=> Fix docker (#1377)

docker-compose-build.yml, docker-compose.yml
=> Switch from nightly docker images to latest for default

Jenkinsfile
=> Add Jenkinspipline for testing

Jenkinsfile
=> Remove escaping for Jenkinsfile

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/AttachmentController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/GeneratorController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/ModelController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/ModelSearchController.java, repository/repository-server-config/src/main/java/org/eclipse/vorto/repository/server/config/config/SwaggerConfiguration.java, repository/repository-web/dist/css/swagger-custom.css, repository/repository-web/dist/partials/rest-api-template.html, repository/repository-web/dist/partials/swagger-template.html
=> Fixes #1311, updated the public api and some improvement on UI

Jenkinsfile
=> Switche escaping of sed

repository/repository-server/src/test/java/org/eclipse/vorto/repository/web/core/ModelRepositoryControllerTest.java
=> Fixes #1418, to fix the test case in repository server module

docker/Generators_Dockerfile, docker/Repository_Dockerfile
=> Fixes #1446, removed jessie-updates reference

pom.xml
=> Fixes #1434, updated http to https

Jenkinsfile
=> Fixes #1454, to update targeturl attributes with proper values

mapping-engine-nodejs/LICENSE.txt, mapping-engine-nodejs/package-lock.json, mapping-engine-nodejs/package.json
Signed-off-by: Somesh Kumar <someshkumarsharma.sks@gmail.com>
=> Fixed license to EPL2.0

mapping-engine-nodejs/README.md
Signed-off-by: Somesh Kumar <someshkumarsharma.sks@gmail.com>
=> Fixes issue-1534, added absolute image urls in readme

docs/tutorials/create_webapp_dashboard.md
Signed-off-by: Tim Grossmann <contact.timgrossmann@gmail.com>
=> Moving the install command to a more visible location

.travis.yml, mapping-engine-nodejs/README.md, mapping-engine-nodejs/package-lock.json, mapping-engine-nodejs/package.json
=> Updated yml to push vorto-mapper to npm

repository/repository-web/dist/partials/details-template.html
=> Remove permissions tab

mapping-engine-nodejs/package-lock.json, mapping-engine-nodejs/package.json
=> Fix issue-1582, update mode-mapper version to 0.11.0

docs/tutorials/connect_javadevice.md, docs/tutorials/mqtt-python.md
=> add error message proposal python and java tutorial

core-bundles/docs/dsl_grammar_datatype.md, core-bundles/docs/dsl_grammar_functionblock.md, core-bundles/docs/dsl_grammar_infomodel.md, core-bundles/docs/dsl_grammar_mapping.md, core-bundles/docs/quickhelp_dsl.md
=> Fixes #1594, updated the DSL grammer documentation

docs/gettingstarted.md
- Video for Device Provisioning
- Video for Device Integration
- Video for Sensor Data Visualization
---
=> Adjust Video info and links

repository/repository-core/src/main/java/org/eclipse/vorto/repository/workflow/impl/SimpleWorkflowModel.java, repository/repository-server/src/main/resources/static/index.html, repository/repository-web/dist/js/components/tenantUserManagement.js, repository/repository-web/dist/partials/admin/tenantUserManagement.html
- Change note displayed on release button press of model 
- Open what is vorto in new tab instead of redirect 
- Change Cancel -> Close, Create -> Add in tenant mgmnt
- Change "Create User" to "Add User"
--- 
=> UI changes mentioned in #1614

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelPolicyManager.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/AttachmentController.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/web/core/ModelRepositoryControllerTest.java
=> Fixes #1410 - API allows access to resources without Auth token

repository/repository-core/src/main/java/org/eclipse/vorto/repository/tenant/RestrictTenantPerOwnerException.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/tenant/TenantService.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/tenant/TenantManagementController.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/tenant/TenantServiceTest.java, repository/repository-server/src/main/resources/application.yml, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/it/AbstractIntegrationTest.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/it/ApplicationConfig.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/it/TenantServiceIntegrationTest.java
=> Restrict_user_to_own_only_2_repository

repository/repository-server/src/main/resources/static/index.html
- Same GDPR Cookie Consent Banner as with the Webpage
---
=> Add cookie consent banner

repository/repository-web/dist/partials/details-template.html, repository/repository-web/dist/partials/search-template.html
=> Fixes #1613

mapping-engine/mapping-serializer/src/main/java/org/eclipse/vorto/mapping/engine/serializer/FunctionblockMappingSerializer.xtend, mapping-engine/mapping-serializer/src/main/java/org/eclipse/vorto/mapping/engine/serializer/InformationModelMappingSerializer.xtend, repository/repository-core/src/main/java/org/eclipse/vorto/repository/conversion/ModelIdToModelContentConverter.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/IModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/ModelInfo.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/ModelController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/core/ModelRepositoryController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/core/PayloadMappingController.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/controller/PayloadMappingControllerTest.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/MappingTest.java, repository/repository-web/dist/js/controllers/detailsController.js, repository/repository-web/dist/partials/details-template.html
Allows to create multiple mappings with same target platform key
=> Simplified payload mapping creator dialog.

repository/repository-web/dist/js/controllers/detailsController.js, repository/repository-web/dist/partials/details-template.html
=> Fixes #1627

Jenkinsfile
=> Correct way to get AWS credentials.

Jenkinsfile
=> Fixes #1715, updated the Jenkinsfile

generators/generator-boschiotsuite/boschiotsuite-cloud/src/test/java/org/eclipse/vorto/codegen/bosch/templates/ProvisionDeviceScriptTemplateTest.xtend
=> Fix generator unit test error on windows machines.

repository/repository-web/dist/partials/settings-template.html
=> Fixes #1764 - Error exporting models under account settings.

repository/repository-elasticsearch/src/main/java/org/eclipse/vorto/repository/search/ElasticSearchService.java, repository/repository-elasticsearch/src/main/java/org/eclipse/vorto/repository/search/extractor/BasicIndexFieldExtractor.java
=> Fixes #1738 - Search with elastic search is case sensitive

repository/repository-server/src/main/resources/static/index.html, repository/repository-web/dist/js/controllers/detailsController.js, repository/repository-web/dist/partials/admin-template.html, repository/repository-web/dist/partials/admin/createOrUpdateTenant.html, repository/repository-web/dist/partials/admin/createOrUpdateUser.html, repository/repository-web/dist/partials/admin/createTenant.html, repository/repository-web/dist/partials/admin/tenantUserManagement.html, repository/repository-web/dist/partials/details-template.html, repository/repository-web/dist/partials/generators-template.html, repository/repository-web/dist/partials/import-template.html, repository/repository-web/dist/partials/mapping/mappingcreator.html
=> Add Help Icon and Getting Started link

repository/migration/migration_0.11.md
=> Update migration guides to include note about images

docs/specs/vorto_repository-1.0.yml, docs/tutorials/create_openapi.md, docs/tutorials/create_thing.md, docs/tutorials/create_webapp_dashboard.md, docs/tutorials/mqtt-python.md, plugin-sdk/plugin-api/Readme.md
=> Changed RaspberryPiTutorial to RaspberryPi. Fixed link to dev system.

mapping-engine/Readme.md
=> Link Mapping Syntax

docs/release-notes.md
- Adjusted intro text which gives quick info about major changes
- Adjusted spacing of release notes to be better readable
- Added highlighting of most important parts
--- 
=> Adjust release notes

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/AbstractRepositoryController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/ModelController.java, utilities/dsl-reader/src/test/java/org/eclipse/vorto/utilities/ModelSerializerTest.java
=> Fix problem when download models with cross-tenant references.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/AttachmentController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/GenericGeneratorController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/ModelController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/ModelSearchController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/plugins/BoschIotSuitePluginController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/plugins/EclipseDittoPluginController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/plugins/EclipseHonoPluginController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/plugins/OpenAPIPluginController.java
=> Fixes #1806

repository/repository-web/dist/js/controllers/controller.js
=> Fixes #1803 - Login screen is shown upon /#/login for logged in user

repository/repository-web/dist/partials/details-template.html
=> Fix issue-1697 discussions tab

docs/specs/vorto_importer_plugin-2.0.yml
=> Fixes #1810 - Fix open api yml for plugins. Missing query param

repository/repository-web/dist/css/style.css
- Fix img distortion in search 
- Adjust placement of device img
--- 
=> Fixes image distortion in search page

Readme.md, docs/gettingstarted.md, docs/tutorials/connect_esp8266.md, docs/tutorials/connect_javadevice.md, docs/tutorials/create_openapi.md, docs/tutorials/create_thing.md, docs/tutorials/create_webapp_dashboard.md, docs/tutorials/describe_device-in-5min.md, docs/tutorials/describe_device_with_eclipse_ide.md, docs/tutorials/describe_tisensor.md, docs/tutorials/managing_collaborators.md, docs/tutorials/managing_namespaces.md, docs/tutorials/mqtt-python.md, docs/tutorials/publishing_models.md
- Tutorials
- Getting Started
- README
--- 
=> Add notes for StackOverflow to docs

repository/repository-web/dist/css/style.css
=> Fix CSS for overflowing text

plugin-sdk/plugin-api/pom.xml
=> Fixes #1853, upgraded commons-fileupload library to 1.3.3

repository/repository-web/dist/css/style.css, repository/repository-web/dist/partials/details-template.html
It seems like the attributes `max-height` and `max-width` don't work as expected in Safari and Chrome.
After testing, it seems like simply using CSS for it does the trick.
---
=> Fix image scaling issue

repository/repository-server/src/main/resources/static/index.html, repository/repository-web/dist/css/style.css
=> Update copyright notice

pom.xml
=> pomfix_ci for master branch

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/parser/AbstractModelParser.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/ModelParserTest.java, repository/repository-core/src/test/resources/sample_models/InfoModelWithoutNamespace.infomodel
=> #1877 fixes

generators/generator-eclipsehono/hono-arduino/src/main/java/org/eclipse/vorto/codegen/hono/arduino/ArduinoEntitySoureTemplate.xtend, generators/generator-eclipsehono/hono-arduino/src/main/java/org/eclipse/vorto/codegen/hono/arduino/ArduinoFbSourceTemplate.xtend, generators/generator-eclipsehono/hono-arduino/src/test/java/org/eclipse/vorto/codegen/hono/arduino/EntitySourceTemplateTest.xtend, generators/generator-eclipsehono/hono-arduino/src/test/java/org/eclipse/vorto/codegen/hono/arduino/FbSourceTemplateTest.xtend
Signed-off-by: Kumar Somesh (INST/ESW2-Sgp) <kuo1sgp@bosch.com>
=> Fixed #1880, c++ arduino code generator

generators/generator-eclipseditto/src/test/java/org/eclipse/vorto/codegen/ditto/java/EclipseDittoGeneratorTest.java, generators/generator-eclipsehono/hono-java/src/test/java/org/eclipse/vorto/codegen/hono/java/EclipseHonoJavaGeneratorTest.java, plugin-sdk/plugin-api/src/test/java/org/eclipse/vorto/plugin/AbstractGeneratorTest.java, plugin-sdk/plugin-api/src/test/resources/dsls/FunctionBlockWithDataType.fbmodel, plugin-sdk/plugin-api/src/test/resources/dsls/InfoModelWithType.infomodel, plugin-sdk/plugin-api/src/test/resources/dsls/SimpleType.type
=> JUnitTests_FileTypeCheck

generators/generator-eclipsehono/hono-arduino/pom.xml, pom.xml
=> JUnitTest2

core-bundles/pom.xml, device-adapter/device-adapter-api/pom.xml, device-adapter/pom.xml, generators/generator-runner/pom.xml, model-runtime/pom.xml, model/pom.xml, plugin-sdk/plugin-generator/generator-runner-spi/pom.xml, pom.xml
=> JUnitTest4

repository/repository-server/src/main/resources/static/index.html, repository/repository-server/src/main/resources/static/repository.js, repository/repository-web/dist/partials/privacypolicy-template.html
=> Fixed #1898, updated Privacy policy for Vorto Repository

repository/repository-web/dist/js/controllers/signUpController.js, repository/repository-web/dist/partials/privacypolicy-dialog.html, repository/repository-web/dist/partials/signup-template.html
=> Fixes #1936 - User can bypass the T&C during first login

repository/repository-core/src/main/java/org/eclipse/vorto/repository/account/impl/DefaultUserAccountService.java
=> Fixes #1944 - BUG: As a collaborator I am unable to delete my account

docs/specs/vorto_repository-1.0.yml
=> Fixes#1932_UpdateOpenAPISearchExpression

docker/docker_push
=> Fixes#1956_Docker_images_not_getting_pushed_for_release_tags

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/ImportController.java
=> Fixes #1948 - Reindex of database not working during import/upload

docker/Readme.md
=> Fixes #1777_Circular_reference_in_Vorto_Docker_Images

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/utils/BulkUploadHelper.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/importer/ModelBulkImportTest.java
=> Fixes #1967_Unhandled_exception_while_parsing_zip_file

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/IModelRepositoryFactory.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepositoryEventListener.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepositoryFactory.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/search/ISearchService.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/search/impl/SimpleSearchService.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/AbstractIntegrationTest.java, repository/repository-elasticsearch/src/main/java/org/eclipse/vorto/repository/search/ElasticSearchService.java
=> Fixes #1960 - Collaborators model not anonymized upon account deletion

repository/Readme.md, repository/repository-server/Readme.md
=> Fixes #1983, updated readme to run Eclipse Vorto repository locally

core-bundles/meta-model/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/ModelConversionUtils.java, plugin-sdk/plugin-generator/generator-api/src/main/java/org/eclipse/vorto/codegen/utils/Utils.java, plugin-sdk/plugin-generator/generator-api/src/test/java/org/eclipse/vorto/codegen/utils/UtilsTest.java, utilities/dsl-reader/src/test/java/org/eclipse/vorto/utilities/ModelReaderTest.java, utilities/dsl-reader/src/test/resources/dsls/superTypeTestCases/GenericFunctionBlock.fbmodel, utilities/dsl-reader/src/test/resources/dsls/superTypeTestCases/SecondFunctionBlock.fbmodel, utilities/dsl-reader/src/test/resources/dsls/superTypeTestCases/TestFunctionBlockWithEntity.fbmodel, utilities/dsl-reader/src/test/resources/dsls/superTypeTestCases/TestInfomodelWithEntity.infomodel
=> Fixes #1954_Recursive_walk_through_in_generator_plugin

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepositoryEventListener.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/utils/ModelSearchUtil.java, repository/repository-elasticsearch/src/main/java/org/eclipse/vorto/repository/search/ElasticSearchService.java, repository/repository-elasticsearch/src/main/java/org/eclipse/vorto/repository/search/extractor/BasicIndexFieldExtractor.java
=> Fix for modified-by anonymization

Jenkinsfile
=> Fixes #2000, jenkins pipeline updated

.travis.yml
=> Docker_Tag_Update_Changes

generators/generator-runner/Readme.md
=> Fixed #1975: Improved documentation

generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/templates/OpenAPITemplate.xtend
Signed-off-by: philbuettner <philippe.buettner@bosch.com>
=> Fixes #1964: Updated reference

model-conversion/src/main/java/org/eclipse/vorto/model/conversion/ModelContentToEcoreConverter.java, model-conversion/src/test/java/org/eclipse/vorto/model/conversion/ModelContentToEcoreConverterTest.java
=> Fixes#2004_Code_generators_ignoring_multiple_keyword

generators/generator-runner/Readme.md
Added some more details to get this project running.
=> Fixes #1975: Added information about packaging 

.travis.yml, build-scripts/repackage-deploy-repo.sh, docker/docker_push
=> Fixed Issue-2016, docker push

generators/generator-runner/pom.xml, plugin-sdk/pom.xml, pom.xml, repository/pom.xml
=> Fixed #2026, CVE vulnerability fixed by tomcat-embed-core upgrade

generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/templates/OpenAPITemplate.xtend
=> Fixes #1964: Add missing resources

mapping-engine-nodejs/README.md, mapping-engine-nodejs/package.json
=> Fixed #2059, updated the documentation for vorto-metamorph npm package

model-conversion/src/main/java/org/eclipse/vorto/model/conversion/IModelConverter.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/conversion/ModelIdToModelContentConverter.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/IModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/conversion/ModelIdToModelContentConverterTest.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/ModelRepositoryTest.java, repository/repository-core/src/test/resources/sample_models/Color6.type, repository/repository-core/src/test/resources/sample_models/Color7.type
=> Introduce latest tag to get models through the API. Fixes #1878

repository/repository-server/src/main/java/org/eclipse/vorto/repository/web/VortoErrorHandler.java, repository/repository-server/src/main/resources/static/error/error-template.html
=> 1132 Added a custom error page for 4xx and 5xx errors

repository/repository-server/src/main/resources/static/error/error-template.html
=> Fix image links on error page. Fixes #2072

.travis.yml, build-scripts/repackage-deploy-repo.sh, repository/repository-server/src/main/resources/vorto-repository-config-mysql.json
=> Fixed #2076, added a deployment script to deploy repo in beanstalk

repository/repository-java-client/src/main/java/org/eclipse/vorto/repository/client/generation/GeneratorUrlBuilder.java, repository/repository-java-client/src/main/java/org/eclipse/vorto/repository/client/impl/DefaultRepositoryClient.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/client/generation/GeneratorUrlBuilderTest.java
First part of #2104 - this fixes the URL building in the Java Client. 
=> Fixed URL building for generators. Fixes #2104

generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/templates/OpenAPITemplate.xtend
=> Fixes #2111 OpenAPI-Generator example value

Jenkinsfile
=> Fixed #2133, notify github correctly on successfull compliance scan

Jenkinsfile
=> Fixed #2149, fail build incase of build failure and notify github

docs/specs/vorto_repository-1.0.yml
Signed-off-by: Tobias Gauss <tobias.gauss@bosch-si.com>
=> Added missing property type description. Fixes #2116

generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/templates/OpenAPITemplate.xtend
=> Fixes #2170, Update OpenAPI template

generators/generator-boschiotsuite/boschiotsuite-cloud/src/test/java/org/eclipse/vorto/codegen/bosch/templates/ProvisionDeviceScriptTemplateTest.xtend, generators/generator-eclipsehono/hono-arduino/pom.xml, generators/generator-eclipsehono/hono-arduino/src/test/java/org/eclipse/vorto/codegen/hono/arduino/EclipseHonoArduinoGeneratorTest.java, plugin-sdk/plugin-api/pom.xml, plugin-sdk/plugin-api/src/test/java/org/eclipse/vorto/plugin/AbstractGeneratorTest.java, plugin-sdk/plugin-api/src/test/java/org/eclipse/vorto/plugin/generator/TestUtils.java
=> Fixed #2167, hono ardunio test cases

generators/generator-openapi/src/main/java/org/eclipse/vorto/codegen/openapi/templates/OpenAPITemplate.xtend
=> Fixes #2170, Review OpenAPI Template

pom.xml
=> Updated reference to tomcat-embed to 8.5.50 - latest in date

generators/generator-eclipseditto/src/main/java/org/eclipse/vorto/codegen/ditto/EclipseDittoGenerator.java, generators/generator-lambda/sam-local.template
Also added a template file to run generators locally with SAM local.
=> Added configKey for target parameter to EclipseDittoGenerator. Fixes #2204.

repository/repository-server/src/main/java/org/eclipse/vorto/repository/web/VortoErrorHandler.java
=> Changed resource loading for error page. #2206

docker/Repository_Dockerfile
=> Change URL to HTTPS. Fixes #2232.

core-bundles/meta-model/org.eclipse.vorto.core/src/org/eclipse/vorto/core/api/model/ModelConversionUtils.java, utilities/dsl-reader/src/test/java/org/eclipse/vorto/utilities/ModelReaderTest.java
Signed-off-by: Tobias Gauss <tobias.gauss@bosch-si.com>
=> Prevent properties from being added multiple times. Fixes #2172

repository/repository-server/src/main/resources/application.yml
=> Added YML as supported attachment type.

generators/generator-boschiotsuite/boschiotsuite-cloud/src/main/java/org/eclipse/vorto/codegen/bosch/templates/BoschGeneratorConfigUI.xtend, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java
=> Fixes #2269.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/account/IUserAccountService.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/account/impl/DefaultUserAccountService.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/domain/User.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/oauth/AbstractOAuthProvider.java, repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIDOAuthProvider.java, repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderV1.java, repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderV2.java, repository/repository-oauth-boschid/src/test/java/org/eclipse/vorto/repository/oauth/HydraTokenVerifierTest.java, repository/repository-oauth-boschid/src/test/java/org/eclipse/vorto/repository/oauth/LegacyTokenVerificationTest.java, repository/repository-server/src/main/resources/application.yml
=> Fixed BoschIoTSuite OAuth. Fixes #2256.

repository/repository-web/dist/partials/admin/createTenant.html
=> Added official namespace disclaimer. Fixes #2264.

docs/release-notes.md
=> Added 0.13 release notes.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/ModelRepositoryTest.java
=> Fixes #1878.

repository/repository-java-client/src/main/java/org/eclipse/vorto/repository/client/RepositoryClientBuilder.java, repository/repository-java-client/src/main/java/org/eclipse/vorto/repository/client/impl/ImplementationBase.java
=> Added configuration for proxy username and password. Fixes #2203.

generators/generator-boschiotsuite/Readme.md
#2289 
Signed-off-by: Ineskouka <inesnatacha.koukapene@bosch.io>
=> Documentation URLs is fixed now.

.travis.yml
=> Fix lambda timeout reset after deployment.

Jenkinsfile
=> fixed wrong parameter order

repository/repository-web/dist/js/controllers/manage/namespaceUserManagement.js
=> Removed autocomplete when only 1 user match returned by search

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/Attachment.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/core/ModelRepositoryController.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/ModelRepositoryAttachmentTest.java
=> UX/2305 Cannot change image of my vorto model

repository/repository-web/dist/partials/details-template.html
Added literal "server time" next to model comments date/time
=> bug/2318 Time one hour off in the comments

pom.xml
=> Updated tomcat version. Fixes #2324.

build-scripts/repackage-deploy-repo.sh
=> Change deployment pipeline to deploy from branch deployment to dev env.

.travis.yml
=> Trigger the deployment script from the deployment branch.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/AbstractRepositoryOperation.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepositoryFactory.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/RequestRepositorySessionHelper.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/RequestRepositorySessionHelperTest.java
=> JCR Session handling optimization. Fixes #2320

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/backup/BackupController.java
* re-added backup endpoint for whole repository (sysadmin only)
* renamed restore endpoint for whole repository to "namespaces" (instead of "tenants")
=> bug/2339 Restore backup endpoint

generators/generator-lambda/generator-lambda-executor/pom.xml, generators/generator-lambda/generator-lambda-executor/src/main/java/org/eclipse/vorto/plugins/generator/lambda/executor/GeneratorExecutionHandler.java, generators/generator-lambda/generator-lambda-plugininfo/pom.xml, generators/generator-lambda/generator-lambda-plugininfo/src/main/java/org/eclipse/vorto/plugins/generator/lambda/meta/plugins/plugins/AzureIoTPluginInfo.java, generators/generator-lambda/generator-lambda-plugininfo/src/main/java/org/eclipse/vorto/plugins/generator/lambda/meta/plugins/plugins/GeneratorPluginInfoFactory.java, generators/generator-runner/pom.xml, generators/generator-runner/src/main/java/org/eclipse/vorto/generators/runner/GeneratorConfiguration.java, generators/generator-runner/src/main/resources/generators/azure.properties, plugin-sdk/plugin-generator/generator-runner-spi/pom.xml
=> Reactivate Azure Generator.

.travis.yml, build-scripts/repackage-deploy-repo.sh
=> Deploy from deployment branch. Fixes #2338.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/IModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/AbstractRepositoryOperation.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/RequestRepositorySessionHelper.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/plugin/generator/impl/GeneratedOutputAttachmentHandler.java
=> Fixed elevated session handling

repository/repository-core/src/main/java/org/eclipse/vorto/repository/workflow/impl/SimpleWorkflowModel.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/workflow/impl/functions/BulkApproveFunction.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/workflow/WorkflowTest.java
=> Bulk operation for approving models. Fixes #1982

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/AbstractRepositoryOperation.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/ModelController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/NamespaceController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/core/ModelRepositoryController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/workflow/impl/SimpleWorkflowModel.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/workflow/impl/functions/BulkApproveFunction.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/workflow/WorkflowTest.java
deploying this to prod for tomorrow, so we can replicate with additional server-side logs
=> Bug 2355 save models broken

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/AttachmentController.java
=> Display attachments with no tags. Fixes #2358.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/backup/impl/BackupRestoreService.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/IModelPolicyManager.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelPolicyManager.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepositoryFactory.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/admin/RestorePoliciesController.java
=> Restore access policies mechanism and endpoint added. Fixes #2350

generators/generator-lambda/sam-local.template
=> Fixes #2386

repository/repository-core/src/main/java/org/eclipse/vorto/repository/conversion/ModelIdToModelContentConverter.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/IModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/ModelController.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/ModelRepositoryTest.java
=> Fixed LATEST flag usage for model content. Fixes #2390

Jenkinsfile, sonar-project.properties
=> Changed sonarcloud project.

Jenkinsfile
=> Sonarcloud cleanup

Jenkinsfile
=> update sonarcloud token

Jenkinsfile
=> re-added PR config

docs/vortolang-1.0.md
Signed-off-by: julian <j.feinauer@pragmaticminds.de>
=> Add Function Block Mapping to Spec-TOC.

repository/repository-server/src/main/resources/application-local-dev-mysql.yml
=> Missing file header added. Fixes #2413

repository/pom.xml
=> 2432 Upgrade jQuery to latest version

generators/generator-eclipseditto/pom.xml, mapping-engine/mapping-serializer/pom.xml, plugin-sdk/plugin-generator/generator-runner-spi/pom.xml, plugin-sdk/pom.xml, pom.xml, repository/pom.xml, repository/repository-core/pom.xml, repository/repository-editor/pom.xml, repository/repository-oauth-boschid/pom.xml, repository/repository-oauth-github/pom.xml, repository/repository-server-config/pom.xml, repository/repository-server/pom.xml, utilities/dsl-reader/pom.xml
=> Pom.xml cleanup. Fixes #2383

pom.xml
=> 2423 Update tomcat-embed-core to 8.5.55

repository/repository-web/dist/js/controllers/detailsController.js
=> result handling adapted. result -> result.data. Fixes #2443

docs/tutorials/connect_esp8266.md, docs/tutorials/connect_javadevice.md, docs/tutorials/create_thing.md, docs/tutorials/create_webapp_dashboard.md, docs/tutorials/describe_tisensor.md, docs/tutorials/mqtt-python.md, generators/generator-boschiotsuite/Readme.md, generators/generator-openapi/Readme.md, mapping-engine/docs/mapping_syntax.md, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/listeners/AuthenticationSuccessHandler.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/ui/ModelDetailsResolver.java, repository/repository-java-client/Readme.md, repository/repository-server/src/main/resources/static/error/error-template.html, repository/repository-server/src/main/resources/static/index.html, repository/repository-server/src/main/resources/static/repository.js, repository/repository-web/dist/partials/admin-template.html, repository/repository-web/dist/partials/details-template.html, repository/repository-web/dist/partials/generators-template.html, repository/repository-web/dist/partials/import-template.html, repository/repository-web/dist/partials/mapping/mappingcreator.html, repository/repository-web/dist/partials/search-template.html, repository/repository-web/dist/partials/templates/modelcreation/infomodel_step3.html
* removes bang from location hash so AngularJS URLs are backwards-compatible after framework upgrade
* re-fixes all links again
=> 2457/Redirect requests to new AngularJS notation

generators/generator-eclipsehono/hono-java/src/main/java/org/eclipse/vorto/codegen/hono/java/EclipseHonoJavaGenerator.java, generators/generator-eclipsehono/hono-java/src/test/resources/defaultFileFormat/ConfigPropertiesFunctionBlock.java, generators/generator-eclipsehono/hono-java/src/test/resources/defaultFileFormat/StatusPropertiesFunctionBlock.java, generators/generator-eclipsehono/hono-java/src/test/resources/defaultFileFormat/ValidEntity.java, plugin-sdk/plugin-api/src/main/java/org/eclipse/vorto/plugin/generator/utils/javatemplates/JavaClassFieldGetterTemplate.xtend, plugin-sdk/plugin-api/src/main/java/org/eclipse/vorto/plugin/generator/utils/javatemplates/JavaClassFieldSetterTemplate.xtend, plugin-sdk/plugin-api/src/main/java/org/eclipse/vorto/plugin/utils/Utils.java
=> Fixes #2454.

docs/vortolang-1.0.md
Signed-off-by: Julian Feinauer <j.feinauer@pragmaticminds.de>
=> Issue #2447 Add example how to use measurement unit

repository/pom.xml, repository/repository-oauth-eclipse/pom.xml, repository/repository-oauth-eclipse/src/main/java/org/eclipse/vorto/repository/oauth/EclipseOAuthProviderConfiguration.java, repository/repository-oauth-eclipse/src/main/java/org/eclipse/vorto/repository/oauth/EclipseRepositoryAuthProvider.java, repository/repository-server/src/main/resources/application.yml
Signed-off-by: Julian Feinauer <j.feinauer@pragmaticminds.de>
=> Issue 2330 Added Implementation for Eclipse.org Oauth support.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/UserRepositoryRoleService.java
=> Hotfix for broken sysadmin sql. #2479

repository/repository-oauth-eclipse/src/main/java/org/eclipse/vorto/repository/oauth/EclipseOAuthProviderConfiguration.java, repository/repository-server/pom.xml, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/it/IntegrationTestBase.java
Signed-off-by: julian <j.feinauer@pragmaticminds.de>
=> Add Eclipse OAuth to Server.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/AbstractRepositoryOperation.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepositoryFactory.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/RequestRepositorySessionHelper.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/UnitTestBase.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/search/SearchTestInfrastructure.java, repository/repository-elasticsearch/src/test/java/org/eclipse/vorto/repository/search/SearchTestInfrastructure.java
=> fix access to models for sysadmins

repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderV2.java
=> Ignore authentication for public models

repository/repository-core/src/main/java/org/eclipse/vorto/repository/repositories/NamespaceRoleRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/repositories/PrivilegeRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/repositories/RepositoryRoleRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/repositories/UserRepositoryRoleRepository.java, repository/repository-server-config/src/main/java/org/eclipse/vorto/repository/server/config/config/RepositoryCachingConfiguration.java
=> Caching re-configured. Fixes #2472

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/ApidocController.java
Signed-off-by: henry-lp <tailp@kth.se>
This PR fixes the violations for the following SonarQube rules:
https://rules.sonarsource.com/java/RSPEC-4973
If you do no want to receive automated PRs for SonarQube warnings, reply to this PR with 'STOP'
=> Proposal for patching SonarQube rule 4973

repository/repository-core/src/main/java/org/eclipse/vorto/repository/repositories/UserNamespaceRoleRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/UserNamespaceRoleService.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/UserUtil.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/NamespaceController.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/util/NamespaceValidator.java
Functional fix: the namespace search was supposed to not only show public namespaces, but also private namespaces where the authenticated user has any role.
=> 2462_followup

repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/AbstractUITest.java
=> Properties added. Fixes #2507

repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderAuthCode.java, repository/repository-oauth-boschid/src/test/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderAuthCodeTest.java, repository/repository-server/src/main/resources/static/repository.js
=> Fixed redirect after login and added unit tests

repository/repository-oauth-boschid/src/test/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderAuthCodeTest.java
=> Fixes #2489. added unit test.

repository/repository-server/src/main/resources/static/repository.js
=> Fix redirect parameters

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/HomeController.java
=> fixed NPE in signup process

repository/repository-server/src/main/resources/application-local-dev-mysql.yml
=> disable sql logging on dev

repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/NamespaceService.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/UserNamespaceRoleService.java
=> Fixes #2532.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/api/v1/AbstractGeneratorController.java
=> Fixes #2535. Fix generators

repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderAuthCode.java, repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderConfiguration.java, repository/repository-oauth-github/src/main/java/org/eclipse/vorto/repository/oauth/GithubRepositoryAuthProvider.java
=> Fixes #2536. Fixes authorization initialization after login.

repository/repository-web/dist/js/controllers/detailsController.js
=> Fixes #2541. Fix attachment listing in details view.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/admin/RestorePoliciesController.java
=> #2545 fix namespace resolution

repository/repository-core/src/main/java/org/eclipse/vorto/repository/domain/Namespace.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/domain/User.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/domain/UserNamespaceRoles.java
=> Add database indexes

repository/repository-web/dist/js/controllers/detailsController.js
=> Fixes #2552.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/domain/Namespace.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/domain/UserRepositoryRoles.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/NamespaceService.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/utils/NamespaceUtils.java, repository/repository-web/dist/js/controllers/detailsController.js, repository/repository-web/dist/partials/details-template.html
=> Improve general performance

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepositoryFactory.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/repositories/NamespaceRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/NamespaceService.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/UnitTestBase.java, repository/repository-core/src/test/java/org/eclipse/vorto/repository/core/search/SearchTestInfrastructure.java, repository/repository-elasticsearch/src/test/java/org/eclipse/vorto/repository/search/SearchTestInfrastructure.java
=> improve dependency handling

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java
=> Fixes #2570. Added LATEST handling to /file

repository/repository-core/src/main/java/org/eclipse/vorto/repository/plugin/generator/impl/GeneratedOutputAttachmentHandler.java
=> Do not ignore duplicate parameter values. Fixes #2572

repository/repository-core/src/main/java/org/eclipse/vorto/repository/oauth/AbstractOAuthProviderConfiguration.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/web/security/UserDBAuthoritiesExtractor.java, repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthPrincipalExtractor.java, repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderConfiguration.java
=> Adjust SuiteAuth to use orig_id

repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderAuthCode.java, repository/repository-oauth-boschid/src/test/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderAuthCodeTest.java
=> Ignore failed authentication and continue anonymously

repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderAuthCode.java, repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/CiamIdNotFoundException.java
=> Fixed token evaluation for service integration

repository/repository-oauth-boschid/src/main/java/org/eclipse/vorto/repository/oauth/BoschIoTSuiteOAuthProviderAuthCode.java
=> Renaming SuiteAuth Provider. Fixes #2592.

repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/NamespaceService.java
Some extra logging and safer logic in namespace -> workspace ID resolution
=> namespace_resolution_troubleshoot

repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/NamespaceService.java
This has been urgently deployed to prod yesterday and fixes an issue causing NPEs when resolving namespaces, moreover it adds some logging around the functionality.
=> Namespace resolution troubleshoot

repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/BasicRepositoryUITest.java
=> Conflicts resolved.

repository/repository-elasticsearch/src/main/java/org/eclipse/vorto/repository/search/ElasticSearchService.java
=> Fixes #2549. Increased max search results to 10000.

pom.xml
=> Fixes #2257. Updated developer info.

docs/release-notes.md
=> updated release notes for 1.0

repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/SeleniumVortoHelper.java
=> Broken UI test fixed.

repository/repository-server/src/main/resources/application-local-dev-mysql.yml, repository/repository-server/src/main/resources/application.yml
=> add_ckersten_to_sysadmin

repository/repository-server/src/test/resources/benchmarkTests/apiCallGetModel.jmx
This is a small modification to the jMeter markup, in order to include a test for a payload mapping.
=> Temp mapping no opti

repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/IModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/core/impl/ModelRepository.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/plugin/generator/impl/GeneratedOutputAttachmentHandler.java
=> Fixes #2629.

repository/repository-web/dist/partials/details-template.html
=> Fixes #2658

docs/specs/vorto_repository-1.0.yml, generators/generator-lambda/generator-lambda-executor/dependency-reduced-pom.xml, generators/generator-lambda/generator-lambda-plugininfo/dependency-reduced-pom.xml
=> adjust json schema

Jenkinsfile
=> Migration pipeline and cleanup.

docker/Repository_Dockerfile, docker/config/application.yml, docker/config/vorto-repository-config-mysql.json, docker/scripts/run.py
=> Docker Modeshape Repo in MySQL

core-bundles/language/org.eclipse.vorto.editor.datatype/src/org/eclipse/vorto/editor/datatype/Datatype.xtext, docs/tutorials/managing_namespaces.md, docs/vortolang-1.0.md, repository/repository-core/src/main/java/org/eclipse/vorto/repository/domain/IllegalNamespacePartials.java, repository/repository-core/src/main/java/org/eclipse/vorto/repository/services/ServiceValidationUtil.java, repository/repository-core/src/test/resources/namespaces/invalid_namespaces.txt, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/it/KeywordNamespaceTest.java, repository/repository-server/src/test/resources/models/Location2.fbmodel, repository/repository-server/src/test/resources/models/invalid/InvalidLocation.fbmodel, repository/repository-server/src/test/resources/models/invalid/InvalidLocation10.fbmodel, repository/repository-server/src/test/resources/models/invalid/InvalidLocation3.fbmodel, repository/repository-server/src/test/resources/models/invalid/InvalidLocation4.fbmodel, repository/repository-server/src/test/resources/models/invalid/InvalidLocation5.fbmodel, repository/repository-server/src/test/resources/models/invalid/InvalidLocation6.fbmodel, repository/repository-server/src/test/resources/models/invalid/InvalidLocation7.fbmodel, repository/repository-server/src/test/resources/models/invalid/InvalidLocation8.fbmodel, repository/repository-server/src/test/resources/models/invalid/InvalidLocation9.fbmodel
=> Fixes #2402. Allowing some keywords in namespaces

Jenkinsfile
=> Added missing "D"

repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/it/KeywordNamespaceTest.java, repository/repository-server/src/test/resources/models/Location3.fbmodel
=> added test to cover uppercase namespaces

model/src/main/java/org/eclipse/vorto/model/ModelId.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/AbstractUITest.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/AllTests.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/BasicRepositoryUITest.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/ModelDetailsUITest.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/SeleniumVortoHelper.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/util/CreateModelParams.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/util/CreateModelResultHandler.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/util/CreateNamespaceParams.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/util/RenameModelParams.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/util/RenameModelResultHandler.java, repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/util/ResultHandler.java
Adds a few tests loosely related to the model details UI, and a couple of tools.
=> UI test enrichment

mapping-engine/mapping-converter-binary/pom.xml, mapping-engine/mapping-core/pom.xml, plugin-sdk/pom.xml, pom.xml, repository/pom.xml, repository/repository-elasticsearch/pom.xml, utilities/dsl-reader/pom.xml
=> commons-io upgrade. Fixes #2684

repository/repository-server/src/test/java/org/eclipse/vorto/repository/server/ui/AbstractUITest.java
=> UITest stability fix

pom.xml
=> Fixes #2698.

generators/generator-runner/pom.xml, plugin-sdk/plugin-generator/generator-runner-spi/pom.xml, plugin-sdk/plugin-generator/generator-template/src/main/java/org/eclipse/vorto/codegen/template/runner/PomTemplate.xtend, pom.xml, repository/repository-core/pom.xml, repository/repository-java-client/pom.xml
=> Upgrade httpclient to version 4.5.13

.travis.yml
=> Added java11 deployment for travis

repository/repository-server/pom.xml
=> updated liquibase to 4.1.1

build-scripts/repackage-deploy-repo.sh
=> added config for java11 deployment

build-scripts/repackage-deploy-repo.sh
=> removed ebextensions for java11 deployment

pom.xml
=> binding jar signing to install phase

pom.xml
=> bind jar signing to package phase

pom.xml
=> binding to deploy phase

pom.xml
=> changed both signing plugins to install phase

pom.xml
=> remove jacoco module
